---

# The PostgreSQL PV.
#
# oc create -f postgresql-pv-nfs.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0001
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: infra-1
    path: /exports/pv-0001
  claimRef:
    name: postgresql-claim
    namespace: openrisknet-infra
