---

# The temporary (?) SSO PV.
# Used to allow the fix that prevents Keycloak from starting
#
# oc create -f postgresql-pv-nfs.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0002
spec:
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: infra-1
    path: /exports/pv-0002
