---

# The ImageStream for the 'upstream' Squonk build.
#
# This is the image stream for the container that's used
# to compile Squonk source code. The artifacts are cached
# and the image uised as a soirce when building the runtime images.

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: openshift-squonk-build

parameters:

- name: APP_NAMESPACE
  value: squonk-cicd

objects:

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: openshift-squonk-build
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: informaticsmatters/openshift-squonk-build:latest
      name: latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
