---

# The BuildConfig and output ImageStream for the main Squonk build.
#
# The source image is the Squonk build image (s2i-build-squonk).
# The output image is the 'build-squonk' ImageStream (defined here)

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: squonk-build

parameters:

- name: APP_NAMESPACE
  value: squonk-cicd
- name: APP_SA
  value: squonk

- name: GITHUB_TRIGGER_SECRET
  required: true

- name: CXN_MAVEN_USER
  required: true
- name: CXN_MAVEN_PASSWORD
  required: true

- name: CPU_REQUEST
  value: 1000m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 4Gi
- name: MEM_LIMIT
  value: 16Gi

objects:

# The (input) build container image stream.
# This is the stream that is used to identify the build
# image that's common to all the Squonk components.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: build
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: squonk/s2i:latest
      name: latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

# The incremental (output) container image stream.
# This is the stream that is used to write the
# incremental build to.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: squonk-build
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false

# The Squonk s2i BuildConfig

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: squonk-build
    name: squonk-build
    namespace: ${APP_NAMESPACE}
  spec:
    serviceAccount: ${APP_SA}
    failedBuildsHistoryLimit: 2
    resources:
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEM_REQUEST}
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEM_LIMIT}
    output:
      to:
        kind: ImageStreamTag
        name: squonk-build:latest
        namespace: ${APP_NAMESPACE}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/InformaticsMatters/squonk.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ORG_GRADLE_PROJECT_cxnMavenPassword
          value: ${CXN_MAVEN_PASSWORD}
        - name: ORG_GRADLE_PROJECT_cxnMavenUser
          value: ${CXN_MAVEN_USER}
        from:
          kind: ImageStreamTag
          name: build:latest
          namespace: ${APP_NAMESPACE}
        incremental: true
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_TRIGGER_SECRET}
    - type: ConfigChange
    - type: ImageChange
