---

# The BuildConfig and output ImageStream for Squonk JobExecutor.
#
# Uses thew 'build' container as a source for material,
# injecting material into the runtime container that
# forms the base of the eventual image.

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: jobexecutor-build

parameters:

- name: APP_NAMESPACE
  value: squonk-cicd
- name: APP_SA
  value: squonk

objects:

# The (input) build container image stream.
# This is the stream that is used to identify the build
# image that's the base-image for the JobExecutor.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: jobexecutor-runtime
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: squonk/s2i-jobexecutor:latest
      name: latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

# The (output) container image stream.
# This is the stream that is used to write the
# built JobExecutor image to.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: jobexecutor
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false

# The JobExecutor s2i BuildConfig...

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: jobexecutor-build
    name: jobexecutor-build
    namespace: ${APP_NAMESPACE}
  spec:
    serviceAccount: ${APP_SA}
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: jobexecutor:latest
        namespace: ${APP_NAMESPACE}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: squonk-build:latest
            namespace: ${APP_NAMESPACE}
          # destinationDir is relative to '/tmp/src'
          # '.' is essentially '/tmp/src' in the destination image.
          paths:
          - destinationDir: .
            sourcePath: /tmp/src/components/job-executor/build/libs/job-executor-0.2.0-SNAPSHOT.war
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jobexecutor-runtime:latest
          namespace: ${APP_NAMESPACE}
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: squonk-build:latest
          namespace: ${APP_NAMESPACE}
