---

# The BuildConfig and output ImageStream for Squonk ChemServices/Basic.
#
# Uses the 'build' container as a source for material,
# injecting material into the runtime container that
# forms the base of the eventual image.

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: chemservices-basic-build

parameters:

- name: APP_NAMESPACE
  value: squonk-cicd
- name: APP_SA
  value: squonk

- name: CPU_REQUEST
  value: 500m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 4Gi
- name: MEM_LIMIT
  value: 16Gi

objects:

# The (input) build container image stream.
# This is the stream that is used to identify the build
# image that's the base-image for the runtime container image.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: chemservices-basic-runtime
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: squonk/s2i-chemservices-basic:latest
      name: latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

# The (output) container image stream.
# This is the stream that is used to write the
# built image to.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: chemservices-basic
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false

# The s2i BuildConfig...

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: chemservices-basic-build
    name: chemservices-basic-build
    namespace: ${APP_NAMESPACE}
  spec:
    serviceAccount: ${APP_SA}
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: chemservices-basic:latest
        namespace: ${APP_NAMESPACE}
    runPolicy: Serial
    source:
      images:
      - from:
          kind: ImageStreamTag
          name: squonk-build:latest
          namespace: ${APP_NAMESPACE}
        # destinationDir is relative to '/tmp/src'
        # '.' is essentially '/tmp/src' in the destination image.
        paths:
        - destinationDir: .
          sourcePath: /tmp/src/components/build/chem-services-basic/.
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: chemservices-basic-runtime:latest
          namespace: ${APP_NAMESPACE}
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: squonk-build:latest
          namespace: ${APP_NAMESPACE}
