---

# The BuildConfig and output ImageStream for Squonk CellExecutor.
#
# Uses thew 'build' container as a source for material,
# injecting material into the runtime container that
# forms the base of the eventual image.

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: cellexecutor-build

parameters:

- name: APP_NAMESPACE
  value: squonk-cicd
- name: APP_SA
  value: squonk

objects:

# The (input) build container image stream.
# This is the stream that is used to identify the build
# image that's the base-image for the CellExecutor.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: cellexecutor-runtime
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: squonk/s2i-cellexecutor:latest
      name: latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

# The (output) container image stream.
# This is the stream that is used to write the
# built CellExecutor image to.

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: cellexecutor
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false

# The CellExecutor s2i BuildConfig...

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: cellexecutor-build
    name: cellexecutor-build
    namespace: ${APP_NAMESPACE}
  spec:
    serviceAccount: ${APP_SA}
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: cellexecutor:latest
        namespace: ${APP_NAMESPACE}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: squonk-build:latest
            namespace: ${APP_NAMESPACE}
          paths:
          - destinationDir: .
            sourcePath: /tmp/src/components/cell-executor/build/distributions
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cellexecutor-runtime:latest
          namespace: ${APP_NAMESPACE}
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: squonk-build:latest
          namespace: ${APP_NAMESPACE}
