---

# Pickup environment variables that are set
# using `source setenv.sh`...

keycloak_realm: "{{ ansible_env.KEYCLOAK_REALM }}"
keycloak_logout_redirect_to: "{{ ansible_env.KEYCLOAK_LOGOUT_REDIRECT_TO }}"
keycloak_service_user: maanger
keycloak_service_user_password_field: sso-service-password

oc_project: "{{ ansible_env.OC_PROJECT }}"
oc_infra_project: "{{ ansible_env.OC_INFRA_PROJECT }}"
oc_infra_project_display_name: "{{ ansible_env.OC_INFRA_PROJECT_DISPLAY_NAME }}"
oc_infra_sa: "{{ ansible_env.OC_INFRA_SA }}"
oc_master_hostname: "{{ ansible_env.OC_MASTER_HOSTNAME }}"
oc_routes_basename: "{{ ansible_env.OC_ROUTES_BASENAME }}"
oc_admin_password: "{{ ansible_env.OC_ADMIN_PASSWORD }}"
oc_jobexecutor_host: "{{ ansible_env.OC_JOBEXECUTOR_HOST }}"
oc_postgresql_service: "{{ ansible_env.OC_POSTGRESQL_SERVICE }}"
oc_squonk_host: "{{ ansible_env.OC_SQUONK_HOST }}"
oc_squonk_image_tag: "{{ ansible_env.OC_SQUONK_IMAGE_TAG }}"
oc_user: "{{ ansible_env.OC_USER }}"
oc_user_password: "{{ ansible_env.OC_USER_PASSWORD }}"

# Name fo the infrastructure RabbitMQ name
infra_rabbit_name: "rabbitmq"

# If set each deployment of Pods (infrastructure and squonk)
# will be followed by a monitoring step that waits for the
# expected Pods to initialise before moving on to the next step.
wait_for_pods: yes

# The Squonk OpenShift image pull policy.
# One, typically, of "IfNotPresent" or "Always"
image_pull_policy: Always

# Various retry timeouts (seconds)...
pod_ready_timeout: 600
pod_terminate_timeout: 300
pv_create_timeout: 120
pvc_bind_timeout: 120

# Our root Squonk template directory
# (relative to the role_path directory)
t_dir: ../../../templates
