---

# Note  Some of the following variables may be duplicated in the 'infra'
# ----  role's defaults. The de-duplication is necessary as a stand-alone
#       copy of the the infra role existing in the ORN documentation and we
#       want to promote variables using the role defaults as well as sharing
#       them with Squonk deployment. As such the infra role should be easy to
#       lift from here and use independently.
#
#       Being aware that there is some variable duplication is important
#       should you end up changing names of variables or their default
#       values here.

# Variables expected to be defined in the user's environment...

oc_admin_password: "{{ ansible_env.IM_ADMIN_PASSWORD | default('admin', true) }}"
oc_user_password: "{{ ansible_env.IM_DEVELOPER_PASSWORD | default('developer', true) }}"
oc_squonk_client_secret: "{{ ansible_env.IM_SQUONK_CLIENT_SECRET | default('squonk1234', true) }}"
oc_squonk_pod_environment: "{{ ansible_env.IM_SQUONK_POD_ENVIRONMENT | default('', true) }}"

# Other variables...

# About the OpenShift sluster
oc_master_hostname: okd.informaticsmatters.com
oc_master_port: 443
oc_master_url: https://{{ oc_master_hostname }}:{{ oc_master_port }}
oc_routes_basename: apps.okd.informaticsmatters.com

keycloak_realm: squonk
keycloak_server_protocol: https
keycloak_server_url: "{{ keycloak_server_protocol }}://sso.{{ oc_routes_basename }}/auth"
keycloak_logout_redirect_to: http://home.{{ oc_routes_basename }}/
keycloak_ssl_required: external
keycloak_insecure_route: Redirect
keycloak_service_user: manager
keycloak_service_user_password_field: sso-service-password

# Users
oc_admin: admin
oc_user: developer

# Infrastructure material
oc_infra_project: infra
oc_infra_project_display_name: The Infrastructure Project
oc_infra_sa: infra

oc_postgresql_service: db-postgresql

# Name fo the infrastructure RabbitMQ name
oc_infra_rabbit_name: rabbitmq

# Squonk project material
oc_project: squonk
oc_project_display_name: Squonk Applications
oc_project_sa: squonk

oc_squonk_app: squonk-notebook
oc_squonk_host: "{{ oc_squonk_app }}.{{ oc_routes_basename }}"
oc_squonk_nextflow_image: informaticsmatters/nextflow:19.01.1

oc_jobexecutor_client: squonk-jobexecutor
oc_jobexecutor_host: jobexecutor.{{ oc_routes_basename }}

oc_cell_work_pvc_size: 10Gi

oc_squonk_db: squonk
oc_squonk_user: squonk
oc_squonk_user_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters') }}"

# The Squonk OpenShift image pull policy.
# One, typically, of "IfNotPresent" or "Always"
image_pull_policy: IfNotPresent

# Image tags
oc_squonk_cell_image_tag: latest
oc_squonk_chem_image_tag: latest
oc_squonk_core_image_tag: latest
oc_squonk_je_image_tag: latest
oc_squonk_search_image_tag: latest
oc_squonk_portal_image_tag: latest
oc_squonk_flyway_image_tag: latest

# NFS
oc_nfs_server: bastion.informaticsmatters.com
oc_nfs_path: /exports

# Various retry timeouts (seconds)...
pod_ready_timeout: 600
pod_terminate_timeout: 300
pv_create_timeout: 200
pvc_bind_timeout: 200

# Validate certificates
# (with tasks like curl)
validate_certificates: no

# If set each deployment of Pods
# will be followed by a monitoring step that waits for the
# expected Pods to initialise before moving on to the next step.
wait_for_pods: yes
