---

- name: Login (user)
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Get BuildConfigs
  shell: oc get bc
  register: bc_result
  changed_when: False

- name: Create the Squonk s2i Build
  shell: >
    oc process -f {{ role_path }}/files/build-build-config.yaml
    -p APP_NAMESPACE={{ oc_cicd_project }}
    -p APP_SA={{ oc_cicd_project_sa }}
    -p GITHUB_TRIGGER_SECRET={{ oc_cicd_trigger_secret }}
    -p CXN_MAVEN_USER={{ oc_cicd_cxn_maven_user }}
    -p CXN_MAVEN_PASSWORD={{ oc_cicd_cxn_maven_password }}
    | oc create -f -
  when: not bc_result.stdout | regex_search('^squonk-build\s', multiline=True)

- name: Create the Component s2i Builds
  shell: >
    oc process -f {{ role_path }}/files/runtime-{{ item }}-build-config.yaml
    -p APP_NAMESPACE={{ oc_cicd_project }}
    -p APP_SA={{ oc_cicd_project_sa }}
    | oc create -f -
  loop:
  - cellexecutor
  - coreservices
  - flyway
  - jobexecutor
  when: not bc_result.stdout | regex_search('^%s-build\s' % item, multiline=True)
