---

# Preparation and project creation for Squonk CI/CD.

- name: Login (user)
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

# Squonk CI/CD Project

- name: Check the Squonk CI/CD Project
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Create the Squonk CI/CD Project
  shell: >
    oc new-project {{ oc_cicd_project }}
    --display-name='{{ oc_cicd_project_display_name }}'
  when: >
    not projects_result.stdout
    | regex_search('^%s\s' % oc_cicd_project, multiline=True)
