---

- name: Login (admin)
  shell: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Check ImageStreams
  shell: oc get is
  register: is_result
  changed_when: False

# Create BUILD ImageStreams...

- name: Create the Squonk Build ImageStream
  shell: >
    oc process -f {{ role_path }}/files/build-image-stream.yaml
    -p APP_NAMESPACE={{ oc_cicd_project }}
    | oc create -f -
  when: not is_result.stdout | regex_search('^openshift-squonk-build\s', multiline=True)

# Create RUNTIME ImageStreams...

- name: Create the Squonk CellExecutor Runtime ImageStream
  shell: >
    oc process -f {{ role_path }}/files/runtime-image-stream.yaml
    -p APP_NAMESPACE={{ oc_cicd_project }}
    | oc create -f -
  when: not is_result.stdout | regex_search('^openshift-squonk-runtime\s', multiline=True)
