---

# Displays all of our variables known to this Ansible role.
#
# Here we rely on: -
# 1. all Ansible variables starting with "oc_"
# 2. all environment variables that control Ansible variables starting with "IM_"
#
# Not all Ansible variables are fully resolved
# i.e. to know what value an Ansible variable has when it's based on
# an environment variable you have to look at the variable and
#
# For example...
#
# The "oc_admin_password" is defined by the expression: -
# "{{ ansible_env.IM_ADMIN_PASSWORD | default('admin', true) }}"
#
# Here, if IM_ADMIN_PASSWORD is defined in your environment then
# "oc_admin_password" will be given its value. Otherwise it's
# given the value "admin".

- name: Collect our variables
  set_fact:
    oc_vars: "{{ oc_vars|default({})|combine({item: vars[item]}) }}"
  with_items: "{{ vars }}"
  when: item.startswith('oc_')

- name: Collect our Environment
  set_fact:
    im_vars: "{{ im_vars|default({})|combine({item: ansible_env[item]}) }}"
  with_items: "{{ ansible_env }}"
  when: item.startswith('IM_')

- name: Display our environment
  debug:
    var: im_vars

- name: Display our variables
  debug:
    var: oc_vars
