---

# Login and move to the Squonk project
# and then remove any existing poster job
# before deploying a new one (and waiting for completion).

- name: Login (user) ({{ oc_master_url }})
  command: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Squonk Project
  command: oc project {{ oc_project }}
  changed_when: False

- name: Set job-name fact
  set_fact:
    job_name: "{{ oc_p_sd_poster[oc_p_origin].job_name }}"
  changed_when: False

- name: Display job-name
  debug:
    var: job_name
  changed_when: False

- name: Get jobs
  command: oc get jobs
  register: jobs_result
  changed_when: False

- name: Delete existing SD poster job
  command: oc delete jobs/{{ job_name }}
  when: jobs_result.stdout | regex_search('^%s ' % job_name, multiline=True)

- name: Run SD poster job (always)
  shell: >
    oc process
    -f {{ role_path }}/files/post-service-descriptors.yaml
    -p POSTER_SA={{ oc_project_sa }}
    -p POSTER_IMAGE={{ oc_p_sd_poster[oc_p_origin].image }}
    -p POSTER_IMAGE_TAG={{ oc_p_sd_poster[oc_p_origin].tag }}
    -p POSTER_JOB_NAME={{ job_name }}
    -p PULL_POLICY={{ oc_image_pull_policy }}
    | oc create -f -

- name: Wait for SD poster success
  shell: oc describe jobs/{{ job_name }} | grep '1 Succeeded'  | grep 1
  delay: 10
  retries: "{{ (oc_pod_ready_timeout|int / 10)|int }}"
  register: result
  until: result.rc == 0
  changed_when: False
