---

# Login and move to the Squonk project
# and then remove any existing poster job
# before deploying a new one (and waiting for completion).

- name: Login (user)
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

- name: Get jobs
  shell: oc get jobs
  register: jobs_result
  changed_when: False

- name: Delete existing SD poster job
  shell: oc delete jobs/{{ origin }}
  when: jobs_result.stdout | regex_search('^%s ' % origin, multiline=True)

- name: Run SD poster job (always)
  shell: >
    oc process
    -f {{ role_path }}/files/post-service-descriptors.yaml
    -p POSTER_SA={{ oc_project_sa }}
    -p POSTER_IMAGE={{ sd_poster[origin].image }}
    -p POSTER_IMAGE_TAG={{ sd_poster[origin].tag }}
    -p POSTER_JOB_NAME={{ origin }}
    | oc create -f -

- name: Wait for SD poster success
  shell: oc describe jobs/{{ origin }} | grep '1 Succeeded'  | grep 1
  delay: 10
  retries: "{{ (pod_ready_timeout|int / 10)|int }}"
  register: result
  until: result.rc == 0
  changed_when: False
