---

# oc process -f squonk-app-je-route.yaml | oc create -f -
# oc delete routes --selector template=squonk-app-je-route

kind: Template
apiVersion: v1
metadata:
  name: squonk-app-je-route
  annotations:
    description: Squonk Application Route Definition
    tags: squonk,jobexecutor
labels:
  template: squonk-app-je-route
  app: squonk-app-je-route

parameters:

# -------------
# Configuration
# -------------
# Common (not specific to any service)

- name: APP_NAMESPACE
  value: squonk

# ------------
# JobExecutor
# ------------

- name: JE_HOST
  required: true

- name: JE_ACME_ENABLE
  description: >-
    Set to false to avoid exhausting certificate generation request quota.
    Change this to true if/when you are ready to secure the route with
    trusted certificates.
  value: "false"

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: jobexecutor
    namespace: ${APP_NAMESPACE}
    annotations:
      kubernetes.io/tls-acme: ${JE_ACME_ENABLE}
  spec:
    host: ${JE_HOST}
    path: /jobexecutor
    to:
      kind: Service
      name: jobexecutor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
