---

# Squonk Security Context Constraints.
# Essentially we start with the 'restricted' SCC and add what we need.
# For background, refer to the blog article:
#
#   https://blog.openshift.com/understanding-service-accounts-sccs/
#
# And:
#
#   https://docs.openshift.com/container-platform/3.11/
#     admin_guide/manage_scc.html
#
#   https://docs.openshift.com/container-platform/3.11/
#     install_config/persistent_storage/pod_security_context.html
#
# oc process -f squonk-scc.yaml | oc create -f -
# oc delete scc --selector template=scc-squonk

kind: Template
apiVersion: v1
metadata:
 name: scc-squonk
 annotations:
   description: Squonk SCC Definition
   tags: scc,squonk
labels:
  template: scc-squonk
  app: scc-squonk

objects:

- kind: SecurityContextConstraints
  apiVersion: v1
  metadata:
    name: scc-squonk
  allowPrivilegedContainer: false
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: MustRunAs
  fsGroup:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  volumes:
  - "*"
