---

# The Squonk PVCs.
#
# oc process -f squonk-pvc-nfs.yaml | oc create -f -
# oc delete pvc --selector template=squonk-pvc-nfs

kind: Template
apiVersion: v1
metadata:
  name: squonk-persistence-nfs
  annotations:
    description: Squonk PVCs
    tags: squonk,pvc
labels:
  template: squonk-pvc-nfs
  app: squonk-app

parameters:

- name: APP_NAMESPACE
  value: squonk
- name: CELL_WORK_PVC_SIZE
  value: 10Gi

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: squonk-work-dir-pvc
    namespace: ${APP_NAMESPACE}
  spec:
    volumeName: pv-squonk-work-dir
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${CELL_WORK_PVC_SIZE}
