---

# oc process -f squonk-keycloak-init.yaml | oc create -f -
# Most likely you will need to specicify these parameters:
# -p KEYCLOAK_REALM=realmname
# -p ROUTES_BASE_HOSTNAME=hostname
#
# To clean up:
# oc delete secret/squonk-keycloak-config -n squonk
# oc delete job/squonk-client-creator cm/squonk-client-creator
#

kind: Template
apiVersion: v1
metadata:
  name: keycloak-client-create
labels:
  template: keycloak-client-create
message: 'Squonk client created in Keycloak'

parameters:

- displayName: Squonk client secret
  name: SQUONK_CLIENT_SECRET
  required: true

- displayName: Squonk namespace (Project)
  name: SQUONK_NAMESPACE
  value: squonk

- displayName: Squonk Infrastructure Service Account
  name: INFRA_SA
  value: squonk

- displayName: Notebook ID
  name: NOTEBOOK_ID
  value: squonk-notebook

- displayName: Notebook Name
  name: NOTEBOOK_NAME
  value: Squonk Computational Notebook

- displayName: Notebook Description
  name: NOTEBOOK_DESC
  value: Squonk Computational Notebook

- displayName: JobExecutor ID
  name: JOBEXECUTOR_ID
  value: squonk-jobexecutor

- displayName: JobExecutor Name
  name: JOBEXECUTOR_NAME
  value: Squonk JobExecutor

- displayName: JobExecutor Description
  name: JOBEXECUTOR_DESC
  value: Squonk JobExecutor

- displayName: Base hostname for routes
  name: ROUTES_BASE_HOSTNAME
  value: dev.openrisknet.org

- displayName: Prefix for squonk notebook hostname
  name: ROUTE_PREFIX_NOTEBOOK
  value: squonk-notebook

- displayName: Prefix for squonk jobexecutor hostname
  name: ROUTE_PREFIX_JOBEXECUTOR
  value: jobexecutor

- displayName: Prefix for SSO hostname
  name: ROUTE_PREFIX_SSO
  value: sso

- displayName: Keycloak Realm
  name: KEYCLOAK_REALM
  value: squonk

- displayName: Keycloak Realm SSL Required
  name: KEYCLOAK_SSL_REQUIRED
  value: external

- displayName: Redirect URL after logout
  name: LOGOUT_REDIRECT_TO
  required: true

objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jobexecutor-sso-config
    namespace: ${SQUONK_NAMESPACE}
  data:
    keycloak.json: |
      {
        "realm": "${KEYCLOAK_REALM}",
        "auth-server-url": "https://${ROUTE_PREFIX_SSO}.${ROUTES_BASE_HOSTNAME}/auth",
        "bearer-only": true,
        "ssl-required": "${KEYCLOAK_SSL_REQUIRED}",
        "disable-trust-manager": true,
        "resource": "${JOBEXECUTOR_ID}",
        "use-resource-role-mappings": false,
        "principal-attribute": "preferred_username"
      }
    context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Context>
        <Valve className="org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve"/>
      </Context>
    web.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
          <display-name>Job Executor</display-name>
          <listener>
              <listener-class>org.jboss.weld.environment.servlet.Listener</listener-class>
          </listener>
          <servlet>
              <servlet-name>CamelServlet</servlet-name>
              <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
              <load-on-startup>1</load-on-startup>
          </servlet>
          <servlet-mapping>
              <servlet-name>CamelServlet</servlet-name>
              <url-pattern>/rest/*</url-pattern>
          </servlet-mapping>
          <security-constraint>
              <web-resource-collection>
                  <web-resource-name>jobexecutor</web-resource-name>
                  <url-pattern>/rest/v1/*</url-pattern>
                  <http-method-omission>OPTIONS</http-method-omission>
              </web-resource-collection>
              <auth-constraint>
                  <role-name>standard-user</role-name>
              </auth-constraint>
          </security-constraint>
          <security-constraint>
              <web-resource-collection>
                  <web-resource-name>swagger</web-resource-name>
                  <description>Swagger endpoint</description>
                  <url-pattern>/rest/v1/swagger/*</url-pattern>
              </web-resource-collection>
              <!-- No auth-constraint means everybody has access! -->
          </security-constraint>
          <security-constraint>
              <web-resource-collection>
                  <web-resource-name>ping</web-resource-name>
                  <description>Ping endpoint</description>
                  <url-pattern>/rest/ping</url-pattern>
              </web-resource-collection>
              <!-- No auth-constraint means everybody has access! -->
          </security-constraint>
          <login-config>
              <auth-method>KEYCLOAK</auth-method>
              <realm-name>${KEYCLOAK_REALM}</realm-name>
          </login-config>
          <security-role>
              <role-name>standard-user</role-name>
          </security-role>
      </web-app>

    server.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Server port="8005" shutdown="SHUTDOWN">
        <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
        <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
        <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
        <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
        <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
        <GlobalNamingResources>
          <Resource name="UserDatabase" auth="Container"
                    type="org.apache.catalina.UserDatabase"
                    description="User database that can be updated and saved"
                    factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
                    pathname="conf/tomcat-users.xml" />
        </GlobalNamingResources>
        <Service name="Catalina">
          <Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443"
                      proxyName="${ROUTE_PREFIX_JOBEXECUTOR}.${ROUTES_BASE_HOSTNAME}" proxyPort="443" scheme="https"/>
          <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
          <Engine name="Catalina" defaultHost="localhost">
            <Realm className="org.apache.catalina.realm.LockOutRealm">
              <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
            </Realm>
            <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
              <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
                     prefix="localhost_access_log" suffix=".txt"
                     pattern="%h %l %u %t &quot;%r&quot; %s %b" />
            </Host>
          </Engine>
        </Service>
      </Server>


- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-sso-config
    namespace: ${SQUONK_NAMESPACE}
  data:
    keycloak.json: |
      {
        "realm": "${KEYCLOAK_REALM}",
        "auth-server-url": "https://${ROUTE_PREFIX_SSO}.${ROUTES_BASE_HOSTNAME}/auth",
        "ssl-required": "${KEYCLOAK_SSL_REQUIRED}",
        "disable-trust-manager": true,
        "resource": "${NOTEBOOK_ID}",
        "use-resource-role-mappings": false,
        "credentials": { "secret": "${SQUONK_CLIENT_SECRET}" }
      }
    context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Context>
        <Valve className="org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve"/>
      </Context>

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-client-creator
  data:
    create-squonk-client.sh: |
      #!/bin/bash

      set -e

      KEYCLOAK_URL="https://$ROUTE_PREFIX_SSO.$ROUTES_BASE_HOSTNAME/auth"
      NOTEBOOK_HTTP="http://$ROUTE_PREFIX_NOTEBOOK.$ROUTES_BASE_HOSTNAME"
      NOTEBOOK_HTTPS="https://$ROUTE_PREFIX_NOTEBOOK.$ROUTES_BASE_HOSTNAME"
      JOBEXECUTOR_HTTP="http://$ROUTE_PREFIX_JOBEXECUTOR.$ROUTES_BASE_HOSTNAME"
      JOBEXECUTOR_HTTPS="https://$ROUTE_PREFIX_JOBEXECUTOR.$ROUTES_BASE_HOSTNAME"
      DATA="username=${KEYCLOAK_USER}&password=${KEYCLOAK_PASSWORD}&grant_type=password&client_id=admin-cli"

      NOTEBOOK_CONFIG="{\"clientId\":\"$NOTEBOOK_ID\",
        \"name\":\"$NOTEBOOK_NAME\",
        \"description\":\"$NOTEBOOK_DESC\",
        \"redirectUris\":["\"$NOTEBOOK_HTTPS/portal/*\",\"$NOTEBOOK_HTTP/portal/*\",\"${LOGOUT_REDIRECT_TO}/*\""],
        \"protocol\":\"openid-connect\",
        \"baseUrl\":\"$NOTEBOOK_HTTPS\",
        \"rootUrl\":\"\",
        \"publicClient\":\"false\",
        \"serviceAccountsEnabled\":\"false\",
        \"directAccessGrantsEnabled\":\"false\",
        \"standardFlowEnabled\":\"true\",
        \"secret\":\"$SQUONK_CLIENT_SECRET\",
        \"adminUrl\":\"$NOTEBOOK_HTTPS\"
      }"

      JOBEXECUTOR_CONFIG="{\"clientId\":\"$JOBEXECUTOR_ID\",
        \"name\":\"$JOBEXECUTOR_NAME\",
        \"description\":\"$JOBEXECUTOR_DESC\",
        \"redirectUris\":["\"$JOBEXECUTOR_HTTPS/jobexecutor/*\",\"$JOBEXECUTOR_HTTP/jobexecutor/*\""],
        \"protocol\":\"openid-connect\",
        \"baseUrl\":\"$JOBEXECUTOR_HTTPS\",
        \"rootUrl\":\"\",
        \"publicClient\":\"true\",
        \"serviceAccountsEnabled\":\"true\",
        \"directAccessGrantsEnabled\":\"true\",
        \"standardFlowEnabled\":\"true\",
        \"adminUrl\":\"$JOBEXECUTOR_HTTPS\"
      }"

      echo "Keycloak is at $KEYCLOAK_URL"
      echo "SSO user is $KEYCLOAK_USER"
      echo "Secret is $SQUONK_CLIENT_SECRET"
      echo "Data: $DATA"
      echo "$NOTEBOOK_CONFIG"
      echo "$JOBEXECUTOR_CONFIG"

      TOKEN=$(curl -ks --data "$DATA" "$KEYCLOAK_URL/realms/$KEYCLOAK_REALM/protocol/openid-connect/token" |\
        grep -Po '(?<="access_token":")[^"]*')
      echo "Token: $TOKEN"

      RESULT=$(curl -ks -X POST \
        -d "$NOTEBOOK_CONFIG" \
        -H "Content-Type: application/json" \
        -H "Authorization: bearer $TOKEN" \
        "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients")

      if [ -n "$RESULT" ]; then
          echo "ERROR: Unable to register portal client $NOTEBOOK_ID in realm $KEYCLOAK_REALM: $RESULT"
          exit 1
      else
          echo "Registered client NOTEBOOK_ID in realm $KEYCLOAK_REALM"
      fi

      RESULT=$(curl -ks -X POST \
        -d "$JOBEXECUTOR_CONFIG" \
        -H "Content-Type: application/json" \
        -H "Authorization: bearer $TOKEN" \
        "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients")

      if [ -n "$RESULT" ]; then
          echo "ERROR: Unable to register jobexecutor client $JOBEXECUTOR_ID in realm $KEYCLOAK_REALM: $RESULT"
          exit 1
      else
          echo "Registered client $JOBEXECUTOR_ID in realm $KEYCLOAK_REALM"
      fi

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: squonk-client-creator
  spec:
    template:
      metadata:
        name: squonk-client-creator
      spec:
        serviceAccountName: ${INFRA_SA}
        volumes:
        - name: squonk-client-creator
          configMap:
            name: squonk-client-creator
        containers:
        - name: squonk-client-creator
          env:
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}
          - name: NOTEBOOK_ID
            value: ${NOTEBOOK_ID}
          - name: NOTEBOOK_NAME
            value: ${NOTEBOOK_NAME}
          - name: NOTEBOOK_DESC
            value: ${NOTEBOOK_DESC}
          - name: JOBEXECUTOR_ID
            value: ${JOBEXECUTOR_ID}
          - name: JOBEXECUTOR_NAME
            value: ${JOBEXECUTOR_NAME}
          - name: JOBEXECUTOR_DESC
            value: ${JOBEXECUTOR_DESC}
          - name: SQUONK_CLIENT_SECRET
            value: ${SQUONK_CLIENT_SECRET}
          - name: ROUTES_BASE_HOSTNAME
            value: ${ROUTES_BASE_HOSTNAME}
          - name: ROUTE_PREFIX_NOTEBOOK
            value: ${ROUTE_PREFIX_NOTEBOOK}
          - name: ROUTE_PREFIX_JOBEXECUTOR
            value: ${ROUTE_PREFIX_JOBEXECUTOR}
          - name: ROUTE_PREFIX_SSO
            value: ${ROUTE_PREFIX_SSO}
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: sso-service-user
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: sso-service-password
          image: centos:7
          command:
          - /bin/bash
          - /squonk-client-creator/create-squonk-client.sh
          volumeMounts:
          - mountPath: /squonk-client-creator
            name: squonk-client-creator
        restartPolicy: OnFailure
