---

- hosts: localhost
  vars_files:
  - ../../../env/{{ ansible_env.IM_PARAMETER_FILE }}

  tasks:
  - name: Run the Squonk Role Update Image Task
    include_role:
      name: squonk
      tasks_from: update-image-versions.yaml
