---

- hosts: localhost
  vars_files:
  - ../../../env/{{ ansible_env.IM_PARAMETER_FILE }}

  tasks:
  - name: Run the Squonk Pipeline Validation Tasks
    include_role:
      name: squonk
      tasks_from: validate-pipelines.yaml
