---

# Setup the Keycloak ImageStream
# in the 'openshift' project...

- name: Move to Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Login (admin) ({{ oc_master_url }})
  command: >
    oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Check Keycloak Image Stream
  command: oc get is -n openshift
  register: is_result
  changed_when: False
  when: oc_keycloak_deploy|bool

- name: Deploy Keycloak Image Stream
  command: >
    oc create
    -f {{ role_path }}/files/keycloak-image-stream.json
    -n openshift
  when:
  - oc_keycloak_deploy|bool
  - not is_result.stdout | regex_search('^keycloak\s', multiline=True)
