---

# Deploy Keycloak secrets.

- name: Login (user)
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Check and deploy...

- name: Check Secrets
  shell: oc get secrets
  register: secret_result
  changed_when: False

- name: Deploy Keycloak Secrets
  shell: >
    oc process -f {{ role_path }}/files/keycloak-secrets.yaml
    | oc create -f -
  when: '"keycloak-secrets" not in secret_result.stdout'
