---

# Deploy Keycloak 'manager' secrets.
# Secrets used by applications,
# kept here because they are not directly related to the Keycloak installation.

- name: Login (user)
  command: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Infrastructure Project
  command: oc project {{ oc_infra_project }}
  changed_when: False

# Check and deploy...

- name: Check Secrets
  command: oc get secrets
  register: secret_result
  changed_when: False

- name: Deploy Manager Secrets
  shell: >
    oc process -f {{ role_path }}/files/keycloak-manager-secrets.yaml
    -p MANAGER_PASSWORD={{ oc_keycloak_manager_password }}
    | oc create -f -
  when:
  - '"manager-secrets" not in secret_result.stdout'
  - oc_keycloak_manager_password is defined

# Put the manger password in a '.user' file
# so we can use it with our 'add-keycloak-users' playbook.
# The file must have a line-feed

- name: Write user file
  copy:
    content: "manager {{ oc_keycloak_manager_password }}\n"
    dest: "{{ role_path }}/../../users.user"
  when:
  - '"manager-secrets" not in secret_result.stdout'
  - oc_keycloak_manager_password is defined
