---

# Just run these plays...

- import_tasks: create-project.yaml
- import_tasks: create-service-account.yaml

# Some diagnostic debug...
- name: Display infrastructure volume configuration
  debug:
    msg: >-
      volume_type={{ oc_infra_volume_type }}
      volume_storage_class={{ oc_infra_volume_storage_class }}

# NFS volumes...
- import_tasks: create-nfs-pv-pvc.yaml
  when: oc_infra_volume_type == 'nfs'
# Dynamic volumes...
- import_tasks: create-dynamic-pvc.yaml
  when: oc_infra_volume_type == 'dynamic'
# MiniShift volumes...
- import_tasks: create-minishift-pvc.yaml
  when: oc_infra_volume_type == 'minishift'
- import_tasks: patch-minishift.yaml
  when: oc_infra_volume_type == 'minishift'

# Deploy Keycloak (and its database)
# and create the route...
- import_tasks: keycloak-postgres-deploy.yaml
- import_tasks: keycloak-route.yaml

# Setup the realm, realm manager and expected roles...
- import_tasks: add-keycloak-realm.yaml
- import_tasks: add-keycloak-realm-manager.yaml
- import_tasks: add-keycloak-realm-roles.yaml

# Finally, RabbitMQ is part of the infrastructure...
- import_tasks: rabbitmq-deploy.yaml
