---

# Just run these plays...

- import_tasks: create-project.yaml
- import_tasks: create-service-account.yaml

# Some diagnostic debug...
- name: Display infrastructure volume configuration
  debug:
    msg: >-
      volume_type={{ oc_infra_volume_type }}
      volume_storage_class={{ oc_infra_volume_storage_class }}

# NFS volumes...
- import_tasks: create-nfs-pv-pvc.yaml
  when: oc_infra_volume_type == 'nfs'
- import_tasks: create-backup-nfs-pv-pvc.yaml
  when: oc_infra_backup_volume_type == 'nfs'
# Dynamic volumes...
- import_tasks: create-dynamic-pvc.yaml
  when: oc_infra_volume_type == 'dynamic'
- import_tasks: create-backup-dynamic-pvc.yaml
  when: oc_infra_backup_volume_type == 'dynamic'
# MiniShift volumes (no backup here)...
- import_tasks: create-minishift-pvc.yaml
  when: oc_infra_volume_type == 'minishift'
- import_tasks: patch-minishift.yaml
  when: oc_infra_volume_type == 'minishift'

# Deploy Postgres and (optionally) Keycloak
# and create the Keycloak route...
- import_tasks: postgres-secrets.yaml
- import_tasks: postgres.yaml

- import_tasks: keycloak-secrets.yaml
  when: oc_keycloak_deploy|bool
- import_tasks: keycloak.yaml
  when: oc_keycloak_deploy|bool
- import_tasks: keycloak-route.yaml
  when: oc_keycloak_deploy|bool

# Setup the realm, realm manager and expected roles...
- import_tasks: add-keycloak-realm.yaml
  when: oc_keycloak_deploy|bool
- import_tasks: add-keycloak-realm-manager.yaml
  when: oc_keycloak_deploy|bool
- import_tasks: add-keycloak-realm-roles.yaml
  when: oc_keycloak_deploy|bool

# Finally, RabbitMQ is (an optional) part of the infrastructure...
- import_tasks: rabbitmq-deploy.yaml
  when: oc_rabbitmq_deploy|bool
