---

- name: Move to Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Login (user)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Check Postgres Deployment
  shell: oc get dc
  register: pg_dc_result
  changed_when: False

- name: Create Postgres Deployment
  shell: >
    oc process
    -f {{ role_path }}/files/postgres.yaml
    -p POSTGRESQL_SHARED_BUFFERS={{ postgresql_shared_buffer_size }}
    -p POSTGRES_SA={{ oc_infra_sa }}
    -p PG_CPU_REQUEST={{ oc_infra_postgresql_cpu_request }}
    -p PG_CPU_LIMIT={{ oc_infra_postgresql_cpu_limit }}
    -p PG_MEM_REQUEST={{ oc_infra_postgresql_mem_request }}
    -p PG_MEM_LIMIT={{ oc_infra_postgresql_mem_limit }}
    | oc create -f -
  when: '"db-postgresql" not in pg_dc_result.stdout'

# Wait for running pods

- name: Wait for Pods
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 10
  retries: "{{ (pod_ready_timeout | int / 10) | int }}"
  register: result
  until: result.rc == 0
  when: wait_for_pods
  loop:
  - db-postgresql
  changed_when: False

# Deploy backups.
# No point waiting for these - they're cron-jobs!

- name: Get CronJobs
  shell: oc get cronjobs
  register: cj_result
  changed_when: false

- name: Deploy the Hourly Backup CronJob
  shell: >
    oc process
    -f {{ role_path }}/files/postgres-backup-hourly.yaml
    -p BACKUP_SCHEDULE="{{ oc_infra_backup_hourly_schedule }}"
    -p BACKUP_COUNT={{ oc_infra_backup_hourly_count }}
    -p BACKUP_SA={{ oc_infra_sa }}
    | oc create -f -
  when:
  - oc_infra_backup_hourly_count|int > 0
  - '"postgresql-backup-hourly" not in cj_result.stdout'

- name: Deploy the Daily Backup CronJob
  shell: >
    oc process
    -f {{ role_path }}/files/postgres-backup-daily.yaml
    -p BACKUP_SCHEDULE="{{ oc_infra_backup_daily_schedule }}"
    -p BACKUP_COUNT={{ oc_infra_backup_daily_count }}
    -p BACKUP_PRIOR_COUNT={{ oc_infra_backup_hourly_count }}
    -p BACKUP_SA={{ oc_infra_sa }}
    | oc create -f -
  when:
  - oc_infra_backup_daily_count|int > 0
  - oc_infra_backup_hourly_count|int > 0
  - '"postgresql-backup-daily" not in cj_result.stdout'
