---

# Deploy Postgres secrets.

- name: Login (user)
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Check and deploy...

- name: Check Secrets
  shell: oc get secrets
  register: secret_result
  changed_when: False

- name: Deploy Postgres Secrets
  shell: >
    oc process -f {{ role_path }}/files/postgres-secrets.yaml
    -p DB_ADMIN_PASSWORD={{ oc_db_admin_password }}
    -p DB_ADMIN_USERNAME={{ oc_db_admin_user }}
    -p DB_DATABASE={{ oc_db_sso_db }}
    -p DB_USERNAME={{ oc_db_sso_db_user }}
    -p DB_PASSWORD={{ oc_db_sso_db_password }}
    | oc create -f -
  when: '"postgresql-secrets" not in secret_result.stdout'
