---

- name: Move to Infrastructure Project
  command: oc project {{ oc_infra_project }}
  changed_when: False

- name: Login (user)
  command: >
    oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Check RabbitMQ Deployment
  command: oc get dc
  register: dc_result
  changed_when: False

- name: Create RabbitMQ Deployment
  shell: >
    oc process
    -f {{ role_path }}/files/rabbitmq.yaml
    -p INFRA_NAMESPACE={{ oc_infra_project }}
    -p INFRA_SA={{ oc_infra_sa }}
    -p RABBITMQ_HOST=rabbitmq.{{ oc_infra_project }}.svc
    -p RABBITMQ_CPU_REQUEST={{ oc_infra_rabbitmq_cpu_request }}
    -p RABBITMQ_MEM_REQUEST={{ oc_infra_rabbitmq_mem_request }}
    | oc create -f -
  when:  not dc_result.stdout | regex_search('^rabbitmq\s', multiline=True)

# Wait for running pods

- name: Wait for RabbitMQ
  shell: oc get po | grep rabbitmq | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (oc_pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  when: oc_wait_for_pods|bool
  changed_when: False
