---

- name: Move to Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Login (user)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Check SSO Route
  shell: oc get routes
  register: routes_result
  changed_when: False

- name: Deploy SSO Route
  shell: >
    oc process
    -f {{ role_path }}/files/sso-route.yaml
    -p HOSTNAME_HTTPS=sso.{{ oc_routes_basename }}
    -p ROUTE_INSECURE_POLICY={{ keycloak_insecure_route }}
    | oc create -f -
  when: not routes_result.stdout | regex_search('^secure-sso\s', multiline=True)
