---

# Get a keycloak token (sets the fact 'keycloak_token').
# Remember that the login user may have changed to admin.

- import_tasks: get-keycloak-token.yaml
  tags:
  - keycloak-users

- name: Query Squonk Users
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/users?username={{ user }}"
    validate_certs: no
    headers:
      Authorization: bearer {{ keycloak_token }}
  register: squonk_users
  vars:
    user: "{{ item.split()[0] }}"
  loop: "{{ lookup('file', '../../' + users_file).split('\n') }}"
  when: users_file is defined
  changed_when: False
  tags:
  - keycloak-users

# The above 'get' is run for each expected user.
# The resultant `squonk_users' variable is a structure
# with each query represented as an element in the 'results' array.
# If the user exists it will have a 'username' property in the 'json'
# array. i.e.
#
#  "results" [{
#    "json": [{
#      "username": "blah"
#
# If the user doe snot exist the 'json' array is empty.
#
# But, to simplify further processing, we'd like a nice flat list.
# So, to collect all known users into a list it's...
#
#   squonk_users | json_query('results[*].json[*].username') | flatten
#
- name: Collect Squonk Users
  set_fact:
    known_users: "{{ squonk_users | json_query('results[*].json[*].username') | flatten }}"
  tags:
  - keycloak-users

# Now, add all the users defined
# that do not already exist...

- name: Add Keycloak Users (that do not exist)
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/users"
    method: POST
    body: '{"username": "{{ user }}", "enabled": "true"}'
    body_format: json
    status_code: 201
    validate_certs: no
    headers:
      Authorization: bearer {{ keycloak_token }}
  vars:
    user: "{{ item.split()[0] }}"
    password: "{{ item.split()[1] }}"
  loop: "{{ lookup('file', '../../' + users_file).split('\n') }}"
  when: user not in known_users
  tags:
  - keycloak-users
