---

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}

# Create PVCs

- name: Check Squonk PV/PVC (dyanmic)
  shell: oc get pvc
  register: s_pvc_result

- name: Create Infrastructure PVCs (dynamic)
  shell: >
    oc process
    -p APP_NAMESPACE={{ oc_project }}
    -p STORAGE_CLASS={{ volume_storage_class }}
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-pvc-dynamic.yaml
    | oc create -f -
  when: '"squonk-work-dir-pvc" not in s_pvc_result.stdout'

# Wait for PVCs to become "Bound"...

- name: Wait for PVCs to become Bound (dyanmic)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  loop:
  - squonk-work-dir-pvc
  when: '"squonk-work-dir-pvc" not in s_pvc_result.stdout'
