---

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

# Create PVCs

- name: Check Squonk PV/PVC (minishift)
  shell: oc get pvc
  register: s_pvc_result
  changed_when: False

- name: Create Squonk PVCs (minishift)
  shell: >
    oc process
    -p APP_NAMESPACE={{ oc_project }}
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-pvc-minishift.yaml
    | oc create -f -
  when: '"squonk-work-dir-pvc" not in s_pvc_result.stdout'

# Wait for PVCs to become "Bound"...

- name: Wait for Squonk PVCs to become Bound (minishift)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  delay: 5
  retries: "{{ (pvc_bind_timeout | int / 5) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - squonk-work-dir-pvc
  when: item not in s_pvc_result.stdout
