---

# Preparation and project creation for Squonk.

- name: Login (user) ({{ oc_master_url }})
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

# Squonk Project

- name: Check the Squonk Project
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Create the Squonk Project
  shell: >
    oc new-project {{ oc_project }}
    --display-name='{{ oc_project_display_name }}'
  when: >
    not projects_result.stdout
    | regex_search('^%s\s' % oc_project, multiline=True)
