---

# Creates the Squonk SA (user) and a related SCC

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

- name: Login (admin)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Get SA
  shell: oc get sa
  register: sa_result
  changed_when: False

- name: Create Squonk SA
  shell: "{{ item }}"
  loop:
  - oc create sa {{ oc_project_sa }}
  when: not sa_result.stdout | regex_search('^%s\s' % oc_project_sa, multiline=True)

- name: Get SCC
  shell: oc get scc
  register: scc_result
  changed_when: False

- name: Create Squonk SCC
  shell: >
    oc process -f {{ role_path }}/files/squonk-scc.yaml
    | oc create -f -
  when: not scc_result.stdout | regex_search('^scc-squonk\s', multiline=True)

- name: Add SA to SCC
  shell: oc adm policy add-scc-to-user scc-squonk -z {{ oc_project_sa }}
  when: not scc_result.stdout | regex_search('^scc-squonk\s', multiline=True)

  # The squonk service account needs the 'anyuid' SCC
  # in order to run DB migration (currently needing to run as root)
  # and the chemservices container...

- name: Add SCC anyuid to squonk SA (flyway)
  shell: oc adm policy add-scc-to-user anyuid -z {{ oc_project_sa }}
  when: not scc_result.stdout | regex_search('^scc-squonk\s', multiline=True)

  # The squonk service account needs 'admin' ROLE
  # so that the OpenShift runner can 'watch' Pods...

- name: Add ROLE admin to squonk SA (flyway)
  shell: oc adm policy add-role-to-user admin -z {{ oc_project_sa }}
  when: not scc_result.stdout | regex_search('^scc-squonk\s', multiline=True)
