---

# Just run these plays...

- import_tasks: pre-flight-checks.yaml

- import_tasks: create-project.yaml
- import_tasks: create-service-account.yaml

# Some diagnostic debug...
- name: Display squonk volume configuration
  debug:
    msg: >-
      volume_type={{ oc_squonk_volume_type }}
      volume_storage_class={{ oc_squonk_volume_storage_class }}

# NFS volumes...
- import_tasks: create-nfs-pv-pvc.yaml
  when: oc_squonk_volume_type == 'nfs'
# Dynamic volumes...
- import_tasks: create-dynamic-pvc.yaml
  when: oc_squonk_volume_type == 'dynamic'
# MiniShift volumes...
- import_tasks: create-minishift-pvc.yaml
  when: oc_squonk_volume_type == 'minishift'

# Prepare for the CI/CD project?
- import_tasks: prepare-cicd.yaml
  when: oc_squonk_image_source_cicd|bool

# Install the application
- import_tasks: squonk-infra-deploy.yaml
- import_tasks: squonk-app-secrets.yaml
- import_tasks: squonk-app-components.yaml
- import_tasks: squonk-app-portal-keycloak.yaml
- import_tasks: squonk-app-je.yaml

# Add users?
- import_tasks: "{{ role_path }}/../infra/tasks/add-keycloak-realm-users.yaml"
  when: users_file is defined
- import_tasks: add-keycloak-nobody-user.yaml
  when: oc_add_nobody_user|bool
