---

# Just run these plays...

- import_tasks: pre-flight-checks.yaml

- import_tasks: create-project.yaml

- import_tasks: create-nfs-pv-pvc.yaml
  when: oc_squonk_volume_type == 'nfs'
- import_tasks: create-dynamic-pvc.yaml
  when: oc_squonk_volume_type == 'dynamic'

- import_tasks: squonk-infra-deploy.yaml
- import_tasks: squonk-app-keycloak.yaml
- import_tasks: squonk-app-keycloak-je.yaml

- import_tasks: get-keycloak-passwords.yaml
- import_tasks: setup-keycloak.yaml
  when: setup_keycloak
