---

# Get a keycloak token (sets the fact 'keycloak_token').
# Remember that the login user may have changed to admin.
#
# The actions for getting the KeyCloak token
# are located in a infra role playbook.

- import_tasks: >
    "{{ role_path }}/../infra/tasks/get-keycloak-token.yaml"

- name: Remove user1
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/users/{{ test_user_id }}"
    method: DELETE
    status_code: 204
    validate_certs: no
    headers:
      Authorization: bearer {{ keycloak_token }}
