---

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}

# Create PVs and PVCs
# The PV and PVC definitions are combined in one template file.

- name: Check Squonk PV/PVC
  shell: oc get pv
  register: s_pv_result

- name: Create Infrastructure PV/PVC
  shell: >
    oc process
    -p APP_NAMESPACE={{ oc_project }}
    -p NFS_SERVER={{ oc_nfs_server }}
    -p NFS_PATH={{ oc_nfs_path }}
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-pvc-nfs.yaml
    | oc create -f -
  when: '"squonk-work-dir" not in s_pv_result.stdout'
