---

# With the Squonk App deployed and initialised
# we can now continue with the JobExecutor deployment...

- name: Login as The Squonk Developer
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

# Deploy...

- name: Check Squonk JobExecutor
  shell: oc get dc
  register: dc_result
  changed_when: False

- name: Deploy Squonk JobExecutor
  shell: >
    oc process
    -f {{ role_path }}/files/squonk-app-keycloak-je.yaml
    -p APP_NAMESPACE={{ oc_project }}
    -p APP_SA={{ oc_project_sa }}
    -p PULL_POLICY={{ image_pull_policy }}
    -p JE_IMAGE_TAG={{ oc_squonk_je_image_tag }}
    -p JE_HOST={{ oc_jobexecutor_host }}
    | oc create -f -
  when: not dc_result.stdout | regex_search('^jobexecutor-keycloak\s', multiline=True)

- name: Wait for Squonk JobExecutor Pod
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  when: wait_for_pods
  loop:
  - jobexecutor-keycloak
  changed_when: False

# Deploy the JobExecutor route

- name: Check Squonk JobExecutor Route
  shell: oc get routes
  register: routes_result
  changed_when: False

- name: Deploy Squonk JobExecutor Route
  shell: >
    oc process
    -f {{ role_path }}/files/squonk-app-je-route.yaml
    -p APP_NAMESPACE={{ oc_project }}
    -p JE_HOST={{ oc_jobexecutor_host }}
    -p JE_ACME_ENABLE={{ enable_acme }}
    | oc create -f -
  when: not routes_result.stdout | regex_search('^jobexecutor\s', multiline=True)
