---

- name: Deploy CellExecutor objects
  k8s:
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  loop:
  - name: cellexecutor-service.yaml.j2
  - name: cellexecutor-deployment.yaml.j2
