---

# With the Squonk App deployed and initialised
# we can now continue with the JobExecutor deployment...

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False
  when: deploy_jobexecutor

- name: Login as The Squonk Developer
  shell: oc login {{ oc_master_hostname }} -u {{ oc_user }} -p {{ oc_user_password }}
  when: deploy_jobexecutor
  changed_when: False

# Deploy...

- name: Check Squonk JobExecutor
  shell: oc get dc
  register: dc_result
  when: deploy_jobexecutor
  changed_when: False

- name: Deploy Squonk JobExecutor
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-app-je.yaml
    -p APP_NAMESPACE={{ oc_project }}
    -p PULL_POLICY={{ image_pull_policy }}
    -p JE_IMAGE_TAG={{ oc_squonk_image_tag }}
    -p JE_HOST={{ oc_jobexecutor_host }}
    | oc create -f -
  when:
  - deploy_jobexecutor
  - not dc_result.stdout | regex_search('^jobexecutor\s', multipline=True)

- name: Wait for Squonk JobExecutor Pod
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  when:
  - deploy_jobexecutor
  - wait_for_pods
  loop:
  - jobexecutor
  changed_when: False
