---

- name: Deploy JobExecutor objects
  k8s:
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  loop:
  - name: jobexecutor-service.yaml.j2
  - name: jobexecutor-deployment.yaml.j2
  - name: jobexecutor-route.yaml.j2
