---

- name: Deploy application Image Streams
  k8s:
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  loop:
  - name: cellexecutor-imagestream.yaml.j2
  - name: chemservices-imagestream.yaml.j2
  - name: coreservices-imagestream.yaml.j2
  - name: jobexecutor-imagestream.yaml.j2

- name: Deploy application objects
  k8s:
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  loop:
  - name: cellexecutor-service.yaml.j2
  - name: cellexecutor-deployment.yaml.j2
  - name: chemservices-service.yaml.j2
  - name: chemservices-deployment.yaml.j2
  - name: coreservices-service.yaml.j2
  - name: coreservices-deployment.yaml.j2
  - name: jobexecutor-service.yaml.j2
  - name: jobexecutor-deployment.yaml.j2
  - name: jobexecutor-route.yaml.j2

- name: Wait for appliction objects
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (oc_pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  when: oc_wait_for_pods|bool
  loop:
  - cellexecutor
  - jobexecutor
  - coreservices
  - chemservices-basic
  changed_when: False
