---

# We do a few things in the infrastructure project first.

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}

- name: Login as Admin
  shell: oc login {{ oc_master_hostname }} -u admin -p {{ oc_admin_password }}

# Prepare PostgreSQL

- name: Check Infrastructure DB
  shell: oc get jobs
  register: j_result

- name: Initialise Infrastructure DB
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-db-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p DATABASE_HOST={{ oc_postgresql_service }}.{{ oc_infra_project }}.svc
    | oc create -f -
  when: '"squonk-database-creator" not in j_result.stdout'

# Prepare RabbitMQ

- name: Initialise RabbitMQ
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-rabbitmq-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p RABBITMQ_HOST=rabbitmq.{{ oc_infra_project }}.svc
    | oc create -f -
  when: '"squonk-rabbitmq-creator" not in j_result.stdout'

# Prepare Keycloak

- name: Initialise Keycloak
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-keycloak-init.yaml
    -p KEYCLOAK_REALM={{ keycloak_realm }}
    -p ROUTES_BASE_HOSTNAME={{ oc_routes_basename }}
    -p LOGOUT_REDIRECT_TO={{ keycloak_logout_redirect_to }}
    | oc create -f -
  when: '"squonk-client-creator" not in j_result.stdout'

# Wait for the pods deployed here (Jobs)
# to reach a "Completed" state...

- name: Wait for Infrastructure DB initialisation
  shell: oc get po | grep squonk-database-creator | grep -v deploy | grep Completed > /dev/null
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  when:
  - wait_for_pods
  - '"squonk-database-creator" not in j_result.stdout'

- name: Wait for RabbitMQ initialisation
  shell: oc get po | grep squonk-rabbitmq-creator | grep -v deploy | grep Completed > /dev/null
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  when:
  - wait_for_pods
  - '"squonk-rabbitmq-creator" not in j_result.stdout'

- name: Wait for Keycloak initialisation
  shell: oc get po | grep squonk-client-creator | grep -v deploy | grep Completed > /dev/null
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  when:
  - wait_for_pods
  - '"squonk-client-creator" not in j_result.stdout'
