---

# We do a few things in the infrastructure project first.

- name: Login as Admin
  shell: oc login {{ oc_master_hostname }} -u admin -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Prepare PostgreSQL

- name: Check Infrastructure DB
  shell: oc get jobs
  register: j_result
  changed_when: False

- name: Initialise Infrastructure DB
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-db-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p DATABASE_HOST={{ oc_postgresql_service }}.{{ oc_infra_project }}.svc
    | oc create -f -
  when: not j_result.stdout | regex_search('^squonk-database-creator\s', multiline=True)

# Prepare RabbitMQ

- name: Initialise RabbitMQ
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-rabbitmq-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p RABBITMQ_HOST=rabbitmq.{{ oc_infra_project }}.svc
    | oc create -f -
  when: not j_result.stdout | regex_search('^squonk-rabbitmq-creator\s', multiline=True)

# Prepare Keycloak

- name: Initialise Keycloak (Client)
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-keycloak-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p KEYCLOAK_REALM={{ keycloak_realm }}
    -p ROUTES_BASE_HOSTNAME={{ oc_routes_basename }}
    -p LOGOUT_REDIRECT_TO={{ keycloak_logout_redirect_to }}
    | oc create -f -
  when: not j_result.stdout | regex_search('^squonk-client-creator\s', multiline=True)

# Wait for the pods deployed here (Jobs)
# to reach a "Completed" state...

- name: Wait for Infrastructure initialisation
  shell: oc describe jobs/{{ item }} | grep Completions | grep 1
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - squonk-rabbitmq-creator
  - squonk-client-creator
  - squonk-database-creator
  when:
  - wait_for_pods
  changed_when: False

# JobExecutor

- name: Check ConfigMaps
  shell: oc get cm
  register: cm_result
  changed_when: False

- name: Initialise Keycloak (JobExecutor)
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-keycloak-je-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p KEYCLOAK_REALM={{ keycloak_realm }}
    -p ROUTES_BASE_HOSTNAME={{ oc_routes_basename }}
    -p LOGOUT_REDIRECT_TO={{ keycloak_logout_redirect_to }}
    | oc create -f -
  when:
  - deploy_jobexecutor
  - not cm_result.stdout | regex_search('^squonk-je-client-creator\s', multiline=True)

#- name: Wait for Infrastructure initialisation (JobExecutor)
#  shell: oc describe jobs/{{ item }} | grep Completions | grep 1
#  delay: 20
#  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
#  register: result
#  until: result.rc == 0
#  loop:
#  - squonk-je-client-creator
#  when:
#  - deploy_jobexecutor
#  - wait_for_pods
#  changed_when: False

