---

# Deploy application-wide secrets.

- name: Login as The Squonk Developer
  shell: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

# Check and deploy...

- name: Check Secrets
  shell: oc get secrets
  register: secret_result
  changed_when: False

- name: Deploy Secrets
  shell: >
    oc process
    -f {{ role_path }}/files/squonk-app-secrets.yaml
    -p APP_NAMESPACE={{ oc_project }}
    -p CELL_POD_ENV="{{ oc_squonk_pod_environment }}"
    | oc create -f -
  when: '"squonk-app-secrets" not in secret_result.stdout'
