---

# We do a few things in the infrastructure project first.

- name: Login as Admin
  shell: oc login {{ oc_master_hostname }} -u admin -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Prepare PostgreSQL

- name: Check Infrastructure DB
  shell: oc get jobs
  register: j_result
  changed_when: False

- name: Initialise Infrastructure DB
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-db-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p DATABASE_HOST={{ oc_postgresql_service }}.{{ oc_infra_project }}.svc
    | oc create -f -
  when: '"squonk-database-creator" not in j_result.stdout'

# Prepare RabbitMQ

- name: Initialise RabbitMQ
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-rabbitmq-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p RABBITMQ_HOST=rabbitmq.{{ oc_infra_project }}.svc
    | oc create -f -
  when: '"squonk-rabbitmq-creator" not in j_result.stdout'

# Prepare Keycloak

- name: Initialise Keycloak
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-infra-keycloak-init.yaml
    -p SQUONK_NAMESPACE={{ oc_project }}
    -p KEYCLOAK_REALM={{ keycloak_realm }}
    -p ROUTES_BASE_HOSTNAME={{ oc_routes_basename }}
    -p LOGOUT_REDIRECT_TO={{ keycloak_logout_redirect_to }}
    | oc create -f -
  when: '"squonk-client-creator" not in j_result.stdout'

# Wait for the pods deployed here (Jobs)
# to reach a "Completed" state...

- name: Wait for Infrastructure initialisation
  shell: oc get po | grep {{ item }} | grep -v deploy | grep Completed > /dev/null
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - squonk-rabbitmq-creator
  - squonk-client-creator
  - squonk-database-creator
  when:
  - wait_for_pods
  - item not in j_result.stdout
  changed_when: False
