---

# With infrastructure deployed and initialised
# we can now continue with Squonk deployment...

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

- name: Login as The Squonk Developer
  shell: oc login {{ oc_master_hostname }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

# Deploy...

- name: Check Squonk
  shell: oc get dc
  register: dc_result
  changed_when: False

- name: Deploy Squonk JobExecutor
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-app/squonk-app-keycloak-je.yaml
    -p APP_NAMESPACE={{ oc_project }}
    -p JE_IMAGE_TAG={{ oc_squonk_image_tag }}
    | oc create -f -
  when: '"jobexecutor" not in dc_result.stdout'

- name: Wait for Squonk JobExecutor Pod
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  when: wait_for_pods
  loop:
  - jobexecutor
  changed_when: False
