---

# Un-deploy (uninstall) the Squonk application.
#
# This consists of un-deploying the application components from the squonk
# project and the related parts of the squonk infrastructure project.

- name: Delete Squonk?
  pause:
    prompt: |-
      Delete Squonk from {{ oc_master_url }}?
      Note that 'delete_database' is {{ delete_database }}.
      Hit return to delete Squonk.
      Hit Ctrl+c and then "a" if you've changed your mind

- name: Login (admin)
  shell: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Check Squonk Project
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Set Squonk Deployment fact
  set_fact:
    squonk_project_exists: "{{ (projects_result.stdout|regex_search('^%s\\s.*Active$' % oc_project, multiline=True) or '')|length > 0 }}"

# Must not continue if it looks like ChemCentral has been deployed.
# If so then you must un-deploy that first

- name: Get Squonk Pods
  shell: oc get po
  register: pods_result
  when: squonk_project_exists

- name: Check ChemCentral Deployment
  fail:
    msg: >-
      ChemCentral appears to be deployed.
      You must remove ChemCentral first.
  when:
  - squonk_project_exists
  - pods_result.stdout | regex_search('^chemcentral', multiline=True)

# To un-deploy squonk, the fastest way is to
# simply delete the squonk project.

- name: Delete Squonk Project
  shell: oc delete project/{{ oc_project }}
  when: squonk_project_exists

- name: Wait for project deletion
  shell: oc get projects
  register: pj_cmd
  retries: 20
  delay: 30
  until: not pj_cmd.stdout | regex_search('^%s\s' % oc_project, multiline=True)
  changed_when: False

# Delete SCC

- name: Check Squonk SCC
  shell: oc get scc
  register: scc_result
  changed_when: False

- name: Delete Squonk SCC
  shell: oc delete scc/scc-squonk
  when: scc_result.stdout | regex_search('^scc-squonk', multiline=True)

# Now undo the stuff in the infrastructure project...

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Remove persistent volumes

- name: Check Squonk PVs (nfs)
  shell: oc get pv
  register: s_pv_result
  changed_when: False
  when: oc_squonk_volume_type == 'nfs'

- name: Delete Squonk PVs (nfs)
  shell: oc delete pv/{{ item }}
  loop:
  - squonk-work-dir
  when:
  - oc_squonk_volume_type == 'nfs'
  - s_pv_result.stdout | regex_search('^%s\s' % item, multiline=True)

- name: Get jobs
  shell: oc get jobs
  register: job_result
  changed_when: False

- name: Delete Jobs
  shell: oc delete job/{{ item }}
  loop:
  - db-creator
  - squonk-rabbitmq-creator
  - squonk-client-creator
  when: job_result.stdout | regex_search('^%s\s' % item, multiline=True)

- name: Wait for Jobs to Terminate
  shell: oc get jobs
  register: j_cmd
  delay: 10
  retries: "{{ (pod_terminate_timeout | int / 10) | int }}"
  until: not j_cmd.stdout | regex_search('^%s\s' % item, multiline=True)
  loop:
  - db-creator
  - squonk-rabbitmq-creator
  - squonk-client-creator
  changed_when: False

- name: Get ConfigMaps
  shell: oc get configmaps
  register: cm_result
  changed_when: False

- name: Delete ConfigMaps
  shell: oc delete cm/{{ item }}
  loop:
  - db-creator
  - squonk-rabbitmq-config
  - squonk-client-creator
  when: cm_result.stdout | regex_search('^%s\s' % item, multiline=True)

# Delete the Squonk Database.
# Caution - this deletes the database as well as the user.

- name: Remove prior temporary Objects (Infrastructure)
  shell: oc delete all,cm --selector template=db-delete
  when: delete_database

- name: Delete Squonk DB
  shell: >
    oc process
    -f {{ role_path }}/../infra/files/infra-db-delete.yaml
    -p DB_HOST={{ oc_postgresql_service }}.{{ oc_infra_project }}.svc
    -p DB={{ oc_squonk_db }}
    -p DB_USER={{ oc_squonk_user }}
    -p INFRA_SA={{ oc_infra_sa }}
    | oc create -f -
  when: delete_database

- name: Wait for User and Database Job
  shell: oc describe jobs/db-deleter | grep '1 Succeeded'
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  changed_when: False
  when: delete_database

# Get a keycloak token (sets the fact 'keycloak_token').
# Remember that the login user may have changed to admin.
#
# The actions for getting the KeyCloak token
# are located in an infra role playbook.

- include_tasks: >
    "{{ role_path }}/../infra/tasks/get-keycloak-token.yaml"
  tags:
  - keycloak-users

# We need the client ID.
# With it we can delete it.

- name: Get Portal Keycloak Client ID
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ oc_squonk_app }}"
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  register: notebook_client_result

- name: Delete Portal Keycloak Client
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/clients/{{ notebook_client_result.json[0].id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  when: notebook_client_result.json

- name: Get JobExecutor Keycloak Client ID
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ oc_jobexecutor_client }}"
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  register: jobexecutor_client_result

- name: Delete JobExecutor Keycloak Client
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/clients/{{ jobexecutor_client_result.json[0].id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  when: jobexecutor_client_result.json

- name: Query Squonk Users
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/users?username={{ user }}"
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  register: squonk_users
  vars:
    user: "{{ item.split()[0] }}"
  loop: "{{ lookup('file', '../../' + users_file).split('\n') }}"
  when: users_file is defined
  changed_when: False
  tags:
  - keycloak-users

# The above 'get' is run for each expected user.
# The resultant `squonk_users' variable is a structure
# with each query represented as an element in the 'results' array.
# If the user exists it will have an 'id' property in the 'json'
# array. i.e.
#
#  "results" [{
#    "json": [{
#      "id": "blah"
#
# If the user does not exist the 'json' array is empty.
#
# To simplify further processing, we'd like a nice flat list.
# So, to collect all known users into a list it's...
#
#   squonk_users | json_query('results[*].json[*].id') | flatten
#
- name: Collect Squonk User IDs
  set_fact:
    known_user_ids: "{{ squonk_users | json_query('results[*].json[*].id') | flatten }}"
  when: users_file is defined
  tags:
  - keycloak-users

- name: Delete Existing Squonk Keycloak Users
  uri:
    url: "{{ keycloak_server_url }}/admin/realms/{{ keycloak_realm }}/users/{{ item }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: bearer {{ keycloak_token }}
    validate_certs: "{{ validate_certificates }}"
  loop: "{{ known_user_ids }}"
  when: users_file is defined
  tags:
  - keycloak-users

# What's left is the database and its tables.
# For now, deleting the database and its tables is a user action.
