---

# Un-deploy (uninstall) the Squonk application.
#
# This consists of un-deploying the application components form the squonk
# project and the related parts of the squonk infrastructure project.

- name: Login (admin)
  shell: oc login {{ oc_master_hostname }} -u admin -p {{ oc_admin_password }}
  changed_when: False

# To un-deploy squonk, the fastest way is to
# simply delete the squonk project.

- name: Check Squonk Project
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Delete Squonk Project
  shell: oc delete project/{{ oc_project }}
  when:  projects_result.stdout | regex_search('^%s\s.*Active$' % oc_project, multiline=True)

- name: Wait for project deletion
  shell: oc get projects
  register: pj_cmd
  retries: 20
  delay: 30
  until: not pj_cmd.stdout | regex_search('^%s\s' % oc_project, multiline=True)
  changed_when: False

# Now undo the stuff in the infrastructure project...

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Get database pod
  shell: oc get pod -o name -l deploymentConfig={{ oc_postgresql_service }}
  register: db_pod
  changed_when: False

# Remove persistent volumes

- name: Check Squonk PVs
  shell: oc get pv
  register: s_pv_result
  changed_when: False

- name: Delete Squonk PVs
  shell: oc delete pv/{{ item }}
  loop:
  - squonk-work-dir
  when: s_pv_result.stdout | regex_search('^%s\s' % item, multiline=True)

- name: Get jobs
  shell: oc get jobs
  register: job_result
  changed_when: False

- name: Delete Jobs
  shell: oc delete job/{{ item }}
  loop:
  - squonk-database-creator
  - squonk-rabbitmq-creator
  - squonk-client-creator
  when: job_result.stdout | regex_search('^%s\s' % item, multiline=True)

- name: Wait for Jobs to Terminate
  shell: oc get jobs
  register: j_cmd
  delay: 10
  retries: "{{ (pod_terminate_timeout | int / 10) | int }}"
  until: not j_cmd.stdout | regex_search('^%s\s' % item, multiline=True)
  loop:
  - squonk-database-creator
  - squonk-rabbitmq-creator
  - squonk-client-creator
  changed_when: False

- name: Get ConfigMaps
  shell: oc get configmaps
  register: cm_result
  changed_when: False

- name: Delete ConfigMaps
  shell: oc delete cm/{{ item }}
  loop:
  - squonk-database-creator
  - squonk-rabbitmq-config
  - squonk-client-creator
  when: cm_result.stdout | regex_search('^%s\s' % item, multiline=True)

# What's left is the database and its tables.
# For now, deleting the database and its tables is a user action.
#
# ...and the client information in Keycloak.
