---

# A pipelines validation script.
# Rules: -
#
#   - One test
#   - Don't fail
#   - Clean up (i.e. remove jobs)
#
# The script can expect the following variables
# to be available (defined by the validate-pipelines playbook)...
#
# - test_user_id
# - test_user_name
# - test_user_password

# Get an access token
# If successful this wil be available as 'je.json.access_token'

- name: Get Temporary JE Access Token
  uri:
    url: "{{ keycloak_server_url}}/realms/{{ keycloak_realm }}/protocol/openid-connect/token"
    body:
    - ["grant_type", "password"]
    - ["client_id", "{{ oc_jobexecutor_client }}"]
    - ["username", "{{ test_user_name }}"]
    - ["password", "{{ test_user_password }}"]
    body_format: form-urlencoded
    method: POST
  register: je

# Run the test