---

# Pickup environment variables that are set
# using `source setenv.sh`...

keycloak_realm: "{{ ansible_env.KEYCLOAK_REALM }}"

oc_infra_project: "{{ ansible_env.OC_INFRA_PROJECT }}"
oc_master_hostname: "{{ ansible_env.OC_MASTER_HOSTNAME }}"
oc_nfs_path: "{{ ansible_env.OC_NFS_PATH }}"
oc_nfs_server: "{{ ansible_env.OC_NFS_SERVER }}"
oc_project: "{{ ansible_env.OC_PROJECT }}"
oc_routes_basename: "{{ ansible_env.OC_ROUTES_BASENAME }}"

# Other variables

postgresql_shared_buffer_size: 1GB

# If set each deployment of Pods (infrastructure and squonk)
# will be followed by a monitoring step that waits for the
# expected Pods to initialise before moving on to the next step.
wait_for_pods: yes

# Here PVs used by the application (the squonk-work-dir for example)
# are returned to an Available state if they're currently
# in a Released state. Note: it is the user's responsibility
# to protect themselves for data loss here. This will inspect the
# "state" of all PVs in the squonk *and* infrastructure projects.
recycle_released_pvs: yes

# Run the PV (NFS) creation?
use_nfs: yes

# Our root Squonk template directory
# (relative to the role_path directory)
t_dir: ../../../templates

# Secrets...

admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64303933666332643963656539663064336631336437386665613461376464353838343262343236
  3063363132303333393334303230346436336664343130390a316366633032393166366137356434
  35343639663435623935316662313962656631613365656336383662303266306238643334393163
  6463383136626466390a326238653235663964316264613164643830663466346263623866643233
  3164
