---

# oc process -f squonk-infra-jobexecutor-init.yaml | oc create -f -
# Most likely you will need to specicify these parameters:
# -p KEYCLOAK_REALM=realmname
# -p ROUTES_BASE_HOSTNAME=hostname
#
# To clean up:
# oc delete secret/squonk-keycloak-config -n squonk
# oc delete job/squonk-client-creator cm/squonk-client-creator
#

kind: Template
apiVersion: v1
metadata:
  name: keycloak-je-client-create
labels:
  template: keycloak-je-client-create
message: 'Squonk JobExecutor client created in Keycloak'

parameters:

- displayName: Squonk namespace (Project)
  name: SQUONK_NAMESPACE
  value: squonk

- displayName: Client ID
  name: CLIENT_ID
  value: squonk-jobexecutor

- displayName: Client Name
  name: CLIENT_NAME
  value: Squonk Job Executor

- displayName: Client Description
  name: CLIENT_DESC
  value: Squonk Job Executor

- displayName: Base hostname for routes
  name: ROUTES_BASE_HOSTNAME
  value: dev.openrisknet.org

- displayName: Prefix for squonk hostname
  name: ROUTE_PREFIX_SQUONK
  value: jobexecutor

- displayName: Prefix for SSO hostname
  name: ROUTE_PREFIX_SSO
  value: sso

- displayName: Keycloak Realm
  name: KEYCLOAK_REALM
  value: squonk

objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-je-sso-config
    namespace: ${SQUONK_NAMESPACE}
  data:
    keycloak.json: |
      {
        "realm": "${KEYCLOAK_REALM}",
        "realm-public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvQ6nwtjHLSRkchUnCHegNhR0HjzATOiDcM46SMsgSH33Ke9+Ij6r7BOBpLm3aNNQuzV2t7PW0R75DjbDBzxqFElUNtDc+nzGj26CDb1gq16vdYgYGwuGNooxh+znwofCEVjceX/BrMDbHwpyHlZ1VnB29G93nq5wNdx2e6bOFC8sCq2/OqTEXkqgKndQ210VYIOuqc5j+PE/T3E/vJB4yAfcO41im/dMAey6MpuRkWL6ABsC5BwQmlo3tzoV+J8G42Oee3IhNdc48XkPe9EN+QcSc44453+5SeUXbvfdaG6vfypow6QQIoLrak3eYoQ/6x7HiJ2l4R9bMHniD/m0rQIDAQAB",
        "bearer-only": true,
        "auth-server-url": "https://${ROUTE_PREFIX_SSO}.${ROUTES_BASE_HOSTNAME}/auth",
        "ssl-required": "none",
        "resource": "squonk-jobexecutor",
        "principal-attribute": "preferred_username"
      }
    context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Context>
          <Valve className="org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve"/>
      </Context>

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-je-client-creator
  data:
    create-squonk-client.sh: |
      #!/bin/bash

      set -e

      # TBD
