# oc process -f squonk-db-init.yaml | oc create -f -
# oc delete all,secrets --selector template=db-prepare
#
# To manually remove the Squonk database artifacts from Postgres open a terminal to the
# postgresql pod, run the psql command and execute these commands:
# drop database squonk;
# drop role squonk;

kind: Template
apiVersion: v1
metadata:
  name: db-prepare
labels:
  template: db-prepare
message: 'Squonk DB created.'

parameters:

- displayName: Squonk user password
  description: Squonk user password
  name: SQUONK_USER_PASSWORD
  from: "[a-zA-Z0-9]{10}"
  generate: expression
  required: true

- displayName: Squonk namespace (Project)
  description: Squonk namespace (Project)
  name: SQUONK_NAMESPACE
  value: squonk

- displayName: Database host
  description: Database host
  name: DATABASE_HOST
  required: true

- displayName: Postgres Admin user
  description: Postgres Admin user
  name: POSTGRESQL_ADMIN_USER
  value: postgres

objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: squonk-database-credentials
    namespace: ${SQUONK_NAMESPACE}
  stringData:
    user-password: ${SQUONK_USER_PASSWORD}
    host: ${DATABASE_HOST}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-database-creator
  data:
    init-squonk-db.sh: |
      #!/bin/bash

      export PGUSER=${POSTGRESQL_ADMIN_USER:-postgres}
      export PGPASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
      export PGHOST=${POSTGRESQL_HOST:-postgres}

      psql --command "CREATE USER squonk WITH PASSWORD '${SQUONK_USER_PASSWORD}'"
      echo "Created users"

      createdb -O squonk squonk
      echo "Created database"

      psql --command "GRANT CONNECT ON DATABASE squonk to squonk"
      psql -d squonk --command "CREATE SCHEMA users AUTHORIZATION squonk"
      psql -d squonk --command "GRANT USAGE ON SCHEMA users TO squonk"
      psql -d squonk --command "CREATE SCHEMA notebooks AUTHORIZATION squonk"
      psql -d squonk --command "GRANT USAGE ON SCHEMA notebooks TO squonk"
      
      echo "Setup complete"

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: squonk-database-creator
  spec:
    template:
      metadata:
        name: squonk-database-creator
      spec:
        volumes:
        - name: squonk-database-creator
          configMap:
            name: squonk-database-creator
        containers:
        - name: squonk-database-creator
          env:
          - name: POSTGRESQL_ADMIN_USER
            value: ${POSTGRESQL_ADMIN_USER}
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: database-admin-password
          - name: SQUONK_USER_PASSWORD
            value: ${SQUONK_USER_PASSWORD}
          - name: POSTGRESQL_HOST
            value: ${DATABASE_HOST}
          image: centos/postgresql-95-centos7
          command:
          - /bin/bash
          - /create-db/init-squonk-db.sh
          volumeMounts:
          - mountPath: /create-db
            name: squonk-database-creator
        restartPolicy: OnFailure
