---

# oc process -f squonk-infra-db-secrets.yaml | oc create -f -
# oc delete secrets --selector template=db-secrets
#
# Used in conjunction with the template 'squonk-infra/infra-db-create.yaml'.
# Use that to create the database and this template t(with the same variables)
# to create the sqounk-project-bound secrets to access it.

kind: Template
apiVersion: v1
metadata:
  name: db-secrets
labels:
  template: db-secrets

parameters:

- displayName: Squonk user
  description: Squonk user
  name: SQUONK_USER
  required: true

- displayName: Squonk user password
  description: Squonk user password
  name: SQUONK_USER_PASSWORD
  required: true

- displayName: Database host
  description: Database host
  name: DATABASE_HOST
  required: true

objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: squonk-database-credentials
  stringData:
    user: ${SQUONK_USER}
    user-password: ${SQUONK_USER_PASSWORD}
    host: ${DATABASE_HOST}
