# oc process -f squonk-app-je-route.yaml | oc create -f -
# oc delete routes --selector template=squonk-app-je-route

kind: Template
apiVersion: v1
metadata:
  name: squonk-app-je-route
  annotations:
    description: Squonk Application Route Definition
    tags: squonk,jobexecutor
labels:
  template: squonk-app-je-route
  app: squonk-app-je-route

parameters:

# -------------
# Configuration
# -------------
# Common (not specific to any service)

- name: APP_NAMESPACE
  value: squonk

# ------------
# JobExecutor
# ------------

- name: JE_HOST
  required: true

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: jobexecutor
    namespace: ${APP_NAMESPACE}
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true if/when you are ready for secure the route with trusted certificates.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: ${JE_HOST}
    to:
      kind: Service
      name: jobexecutor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
