# oc adm policy add-cluster-role-to-user cluster-admin -z default
#
# oc process -f squonk-app-keycloak.yaml | oc create -f -
# oc delete all,cm,pvc,routes,secrets --selector template=squonk-app

# ########## #
# DEPRECATED #
# ########## #
#
# THIS FILE SHOULD NOT BE USED.
# YOU SHOULD BE USING: -
# - squonk-app-components AND
# - squonk-app-portal-keycloak

kind: Template
apiVersion: v1
metadata:
  name: squonk
  annotations:
    description: Squonk Application Service Definition
    tags: squonk,core,cellexecutor,chemservices,coreservices,jobexecutor
labels:
  template: squonk-app
  app: squonk-app

parameters:

# -------------
# Configuration
# -------------
# Common (not specific to any service)

- name: APP_NAMESPACE
  value: squonk
- name: PULL_POLICY
  value: IfNotPresent

# ------
# Flyway (DB Migration)
# ------

- name: FLYWAY_IMAGE_TAG
  value: latest

# ------
# Portal
# ------

- name: PORTAL_IMAGE_TAG
  value: latest
- name: PORTAL_SERVICE_CALLBACK
  value: "http://localhost:8080/portal"
- name: SQUONK_HOST
  required: true
- name: LOGOUT_REDIRECT_TO
  required: true

- name: PORTAL_CPU_REQUEST
  value: 500m
- name: PORTAL_CPU_LIMIT
  value: 1000m
- name: PORTAL_MEM_REQUEST
  value: 500Mi
- name: PORTAL_MEM_LIMIT
  value: 1Gi

# ------------
# ChemServices
# ------------

- name: CHEM_IMAGE_TAG
  value: latest

- name: CHEM_CPU_REQUEST
  value: 100m
- name: CHEM_CPU_LIMIT
  value: 1000m
- name: CHEM_MEM_REQUEST
  value: 500Mi
- name: CHEM_MEM_LIMIT
  value: 1Gi

# ------------
# CoreServices
# ------------

- name: CORE_IMAGE_TAG
  value: latest
- name: CORE_SQUONK_BASIC_CHEM_SERVICES_URL
  value: "http://chemservices:8080"
- name: CORE_SQUONK_DOCKER_SERVICES_DIR
  value: "/var/local/squonk-docker-services"
- name: CORE_SD_PVC_SIZE
  value: 1Gi

- name: CORE_CPU_REQUEST
  value: 100m
- name: CORE_CPU_LIMIT
  value: 1000m
- name: CORE_MEM_REQUEST
  value: 500Mi
- name: CORE_MEM_LIMIT
  value: 500Mi

# ------------
# CellExecutor
# ------------

- name: CELL_IMAGE_TAG
  value: latest
- name: CELL_CONTAINER_RUNNER_TYPE
  value: openshift
- name: CELL_SQUONK_CONTAINER_WORK_DIR
  value: "/squonk/work/docker"
- name: CELL_SQUONK_POD_BASE_NAME
  value: "squonk-cell-pod"
- name: CELL_WORK_PVC_SIZE
  value: 20Gi
- name: CELL_JOB_PROJECT_NAME
  value: squonk
- name: CELL_JOB_LOG_HISTORY
  valuie: 100

- name: CELL_CPU_REQUEST
  value: 100m
- name: CELL_CPU_LIMIT
  value: 1000m
- name: CELL_MEM_REQUEST
  value: 500Mi
- name: CELL_MEM_LIMIT
  value: 500Mi

objects:

# -----------------------------------------------------------------------------
# Postgres Migration (Job)
# -----------------------------------------------------------------------------

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: postgres-migrate
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: postgres-migrate
    template:
      metadata:
        labels:
          name: postgres-migrate
      spec:
        containers:
        - image: squonk/flyway:${FLYWAY_IMAGE_TAG}
          name: postgres-migrate
          env:
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: host
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: user-password
        restartPolicy: OnFailure

# -----------------------------------------------------------------------------
# CoreServices
# -----------------------------------------------------------------------------

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: coreservices
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: coreservices
    template:
      metadata:
        labels:
          name: coreservices
      spec:
        containers:
        - image: squonk/coreservices:${CORE_IMAGE_TAG}
          name: coreservices
          imagePullPolicy: ${PULL_POLICY}
          env:
          - name: RABBITMQ_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: host
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: pass
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: host
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: user-password
          - name: SQUONK_BASIC_CHEM_SERVICES_URL
            value: ${CORE_SQUONK_BASIC_CHEM_SERVICES_URL}
          - name: SQUONK_DOCKER_SERVICES_DIR
            value: ${CORE_SQUONK_DOCKER_SERVICES_DIR}
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /coreservices/rest/ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
#          resources:
#            limits:
#              cpu: ${CORE_CPU_LIMIT}
#              memory: ${CORE_MEM_LIMIT}
#            requests:
#              cpu: ${CORE_CPU_REQUEST}
#              memory: ${CORE_MEM_REQUEST}

- kind: Service
  apiVersion: v1
  metadata:
    name: coreservices
    namespace: ${APP_NAMESPACE}
  spec:
    selector:
      name: coreservices
    ports:
    - name: http
      port: 8080
      targetPort: 8080

# -----------------------------------------------------------------------------
# ChemServices
# -----------------------------------------------------------------------------

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: chemservices-basic
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: chemservices-basic
    template:
      metadata:
        labels:
          name: chemservices-basic
      spec:
        # Initialisation Containers...
        initContainers:
        - image: yauritux/busybox-curl
          name: wait-for-core-before-chem
          command: ['sh', '-c',
            'until (( curl http://coreservices:8080/rest/ping --connect-timeout 5 )); do sleep 2; done']

        # Pod Containers...
        containers:
        - image: squonk/chemservices-basic:${CHEM_IMAGE_TAG}
          name: chemservices-basic
          imagePullPolicy: ${PULL_POLICY}
          env:
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: host
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: user-password
          - name: RABBITMQ_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: host
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: pass
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 4
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 4
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
#          resources:
#            limits:
#              cpu: ${CHEM_CPU_LIMIT}
#              memory: ${CHEM_MEM_LIMIT}
#            requests:
#              cpu: ${CHEM_CPU_REQUEST}
#              memory: ${CHEM_MEM_REQUEST}

- kind: Service
  apiVersion: v1
  metadata:
    name: chemservices
    namespace: ${APP_NAMESPACE}
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      name: chemservices-basic

# -----------------------------------------------------------------------------
# CellExecutor
# -----------------------------------------------------------------------------

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: cellexecutor
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: cellexecutor
    template:
      metadata:
        labels:
          name: cellexecutor
      spec:
        containers:
        - image: squonk/cellexecutor:${CELL_IMAGE_TAG}
          name: cellexecutor
          imagePullPolicy: ${PULL_POLICY}
          env:
          - name: RABBITMQ_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: host
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-rabbitmq-credentials
                key: pass
          - name: SQUONK_CONTAINER_RUNNER_TYPE
            value: ${CELL_CONTAINER_RUNNER_TYPE}
          - name: SQUONK_DOCKER_WORK_DIR
            value: ${CELL_SQUONK_CONTAINER_WORK_DIR}
          - name: SQUONK_CELL_JOB_PROJECT_NAME
            value: ${CELL_JOB_PROJECT_NAME}
          - name: SQUONK_POD_BASE_NAME
            value: ${CELL_SQUONK_POD_BASE_NAME}
          - name: SQUONK_POD_LOG_HISTORY
            value: ${CELL_JOB_LOG_HISTORY}
#          - name: JAVA_OPTS
#            value: '"-Djava.util.logging.config.file=/logging.properties"'
#          resources:
#            limits:
#              cpu: ${CELL_CPU_LIMIT}
#              memory: ${CELL_MEM_LIMIT}
#            requests:
#              cpu: ${CELL_CPU_REQUEST}
#              memory: ${CELL_MEM_REQUEST}
          volumeMounts:
          - mountPath: ${CELL_SQUONK_CONTAINER_WORK_DIR}
            name: squonk-work-dir
        volumes:
        - name: squonk-work-dir
          persistentVolumeClaim:
            claimName: squonk-work-dir-pvc

- kind: Service
  apiVersion: v1
  metadata:
    name: cellexecutor
    namespace: ${APP_NAMESPACE}
  spec:
    selector:
      name: cellexecutor
    ports:
    - name: http
      port: 8080
      targetPort: 8080

# -----------------------------------------------------------------------------
# Portal
# -----------------------------------------------------------------------------

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: portal
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: portal
    template:
      metadata:
        labels:
          name: portal
      spec:
        initContainers:
        - image: yauritux/busybox-curl
          name: wait-for-core-before-portal
          command: ['sh', '-c',
            'until (( curl http://coreservices:8080/rest/ping --connect-timeout 5 )); do sleep 2; done']
        containers:
        - image: squonk/portal:${PORTAL_IMAGE_TAG}
          name: portal
          imagePullPolicy: ${PULL_POLICY}
          env:
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: host
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-database-credentials
                key: user-password
          - name: SERVICE_CALLBACK
            value: ${PORTAL_SERVICE_CALLBACK}
          - name: LOGOUT_REDIRECT_TO
            value: ${LOGOUT_REDIRECT_TO}
          volumeMounts:
            - mountPath: /usr/local/tomcat/conf/context.xml
              name: squonk-sso-config
              subPath: context.xml
              readOnly: true
            - mountPath: /usr/local/tomcat/webapps/portal/WEB-INF/keycloak.json
              name: squonk-sso-config
              subPath: keycloak.json
              readOnly: true
#          readinessProbe:
#            httpGet:
#              path: /portal
#              port: 8080
#            initialDelaySeconds: 30
#            timeoutSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /portal
#              port: 8080
#            initialDelaySeconds: 30
#            timeoutSeconds: 5
#          resources:
#            limits:
#              cpu: ${PORTAL_CPU_LIMIT}
#              memory: ${PORTAL_MEM_LIMIT}
#            requests:
#              cpu: ${PORTAL_CPU_REQUEST}
#              memory: ${PORTAL_MEM_REQUEST}
        volumes:
          - name: squonk-sso-config
            configMap:
              name: squonk-sso-config


- kind: Service
  apiVersion: v1
  metadata:
    name: portal
    namespace: ${APP_NAMESPACE}
  spec:
    selector:
      name: portal
    ports:
    - name: http
      port: 8080
      targetPort: 8080

- kind: Route
  apiVersion: v1
  metadata:
    name: portal
    namespace: ${APP_NAMESPACE}
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true if/when you are ready for secure the route with trusted certificates.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: ${SQUONK_HOST}
    path: /portal
    to:
      kind: Service
      name: portal
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
