---

# oc process -f squonk-infra-jobexecutor-init.yaml | oc create -f -
# Most likely you will need to specicify these parameters:
# -p KEYCLOAK_REALM=realmname
# -p ROUTES_BASE_HOSTNAME=hostname
#
# To clean up:
# oc delete secret/squonk-keycloak-config -n squonk
# oc delete job/squonk-client-creator cm/squonk-client-creator
#

kind: Template
apiVersion: v1
metadata:
  name: keycloak-je-client-create
labels:
  template: keycloak-je-client-create
message: 'Squonk JobExecutor client created in Keycloak'

parameters:

- displayName: Squonk client secret
  name: SQUONK_CLIENT_SECRET
  from: "[a-zA-Z0-9]{32}"
  generate: expression
  required: true

- displayName: Squonk JobExecutor client secret
  name: SQUONK_JE_CLIENT_SECRET
  from: "[a-zA-Z0-9]{32}"
  generate: expression
  required: true

- displayName: Squonk namespace (Project)
  name: SQUONK_NAMESPACE
  value: squonk

- displayName: Client ID
  name: CLIENT_ID
  value: squonk-jobexecutor

- displayName: Client Name
  name: CLIENT_NAME
  value: Squonk Job Executor

- displayName: Client Description
  name: CLIENT_DESC
  value: Squonk Job Executor

- displayName: Base hostname for routes
  name: ROUTES_BASE_HOSTNAME
  value: dev.openrisknet.org

- displayName: Prefix for squonk hostname
  name: ROUTE_PREFIX_SQUONK
  value: jobexecutor

- displayName: Prefix for SSO hostname
  name: ROUTE_PREFIX_SSO
  value: sso

- displayName: Keycloak Realm
  name: KEYCLOAK_REALM
  value: squonk

- displayName: Redirect URL after logout
  name: LOGOUT_REDIRECT_TO
  required: true


objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-je-sso-config
    namespace: ${SQUONK_NAMESPACE}
  data:
    keycloak.json: |
      {
        "realm": "${KEYCLOAK_REALM}",
        "realm-public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuYw5ngO0369xl6FqKUBqGTHjQrdoFg4LWAanBMf1/cLhhBAuD7B4bo8GaLIS+G3cwQZsLZjpcQk54BbCXNu4HUfqJcqus0m0Qo8qfHpCavSbPWAXS9ZCVLxXHmIBBD/pE5ZJidpfT/J5pJEIgPZBPx8/vPNMiZlZrFSPbU7B2bVsgJ3WYq+sPyQ7iUyaHBi8iFXpcz+7GEgO2j0uZoY/F3ECk0qRymySqjaV4kLY6naQ+UXzF3V9fbCAskBVZbIMB5ZgyFd/Au8NAial+E1NsJjEOKvp4+6nrOuZdDfA6M5eFztBRO7aRmcmpx7DK6U+aN64KUXcFvtQrQMpaapmvwIDAQAB",
        "bearer-only": true,
        "auth-server-url": "https://${ROUTE_PREFIX_SSO}.${ROUTES_BASE_HOSTNAME}/auth",
        "ssl-required": "none",
        "resource": "squonk-jobexecutor",
        "principal-attribute": "preferred_username"
      }
    context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Context>
          <Valve className="org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve"/>
      </Context>
    web.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
          <display-name>Job Executor</display-name>
          <listener>
              <listener-class>org.jboss.weld.environment.servlet.Listener</listener-class>
          </listener>
          <!-- Camel servlet -->
          <servlet>
              <servlet-name>CamelServlet</servlet-name>
              <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
              <load-on-startup>1</load-on-startup>
          </servlet>
          <!-- Camel servlet mapping -->
          <servlet-mapping>
              <servlet-name>CamelServlet</servlet-name>
              <url-pattern>/rest/*</url-pattern>
          </servlet-mapping>
          <security-constraint>
              <web-resource-collection>
                  <web-resource-name>jobexecutor</web-resource-name>
                  <url-pattern>/*</url-pattern>
              </web-resource-collection>
              <auth-constraint>
                  <role-name>standard-user</role-name>
              </auth-constraint>
          </security-constraint>
          <login-config>
              <auth-method>KEYCLOAK</auth-method>
              <realm-name>squonk</realm-name>
          </login-config>
          <security-role>
              <role-name>standard-user</role-name>
          </security-role>
      </web-app>

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-je-client-creator
  data:
    create-squonk-je-client.sh: |
      #!/bin/bash

      set -e

      KEYCLOAK_URL="https://$ROUTE_PREFIX_SSO.$ROUTES_BASE_HOSTNAME/auth"
      CLIENT_HTTP="http://$ROUTE_PREFIX_SQUONK.$ROUTES_BASE_HOSTNAME"
      CLIENT_HTTPS="https://$ROUTE_PREFIX_SQUONK.$ROUTES_BASE_HOSTNAME"
      DATA="username=${KEYCLOAK_USER}&password=${KEYCLOAK_PASSWORD}&grant_type=password&client_id=admin-cli"
      CLIENT_CONFIG="{\"clientId\":\"$CLIENT_ID\",
        \"name\":\"$CLIENT_NAME\",
        \"description\":\"$CLIENT_DESC\",
        \"redirectUris\":["\"$CLIENT_HTTPS/portal/*\",\"$CLIENT_HTTP/portal/*\",\"${LOGOUT_REDIRECT_TO}/*\""],
        \"protocol\":\"openid-connect\",
        \"baseUrl\":\"$CLIENT_HTTPS\",
        \"rootUrl\":\"\",
        \"publicClient\":\"false\",
        \"secret\":\"$SQUONK_CLIENT_SECRET\",
        \"adminUrl\":\"$CLIENT_HTTPS\"
      }"

      echo "Keycloak is at $KEYCLOAK_URL"
      echo "SSO user is $KEYCLOAK_USER"
      echo "Secret is $SQUONK_CLIENT_SECRET"
      echo "Data: $DATA"
      echo "$CLIENT_CONFIG"

      TOKEN=$(curl -ks --data "$DATA" "$KEYCLOAK_URL/realms/$KEYCLOAK_REALM/protocol/openid-connect/token" |\
        grep -Po '(?<="access_token":")[^"]*')
      echo "Token: $TOKEN"

      RESULT=$(curl -ks -X POST \
        -d "$CLIENT_CONFIG" \
        -H "Content-Type: application/json" \
        -H "Authorization: bearer $TOKEN" \
        "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients")

      if [ -n "$RESULT" ]; then
          echo "ERROR: Unable to register client $CLIENT_ID in realm $KEYCLOAK_REALM: $RESULT"
          exit 1
      else
          echo "Registered client $CLIENT_ID in realm $KEYCLOAK_REALM"
      fi

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: squonk-je-client-creator
  spec:
    template:
      metadata:
        name: squonk-je-client-creator
      spec:
        volumes:
        - name: squonk-je-client-creator
          configMap:
            name: squonk-je-client-creator
        containers:
        - name: squonk-je-client-creator
          env:
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}
          - name: CLIENT_ID
            value: ${CLIENT_ID}
          - name: CLIENT_NAME
            value: ${CLIENT_NAME}
          - name: CLIENT_DESC
            value: ${CLIENT_DESC}
          - name: SQUONK_CLIENT_SECRET
            value: ${SQUONK_CLIENT_SECRET}
          - name: ROUTES_BASE_HOSTNAME
            value: ${ROUTES_BASE_HOSTNAME}
          - name: ROUTE_PREFIX_SQUONK
            value: ${ROUTE_PREFIX_SQUONK}
          - name: ROUTE_PREFIX_SSO
            value: ${ROUTE_PREFIX_SSO}
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: sso-service-user
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: sso-service-password
          image: centos:7
          command:
          - /bin/bash
          - /squonk-client-creator/create-squonk-client.sh
          volumeMounts:
          - mountPath: /squonk-je-client-creator
            name: squonk-je-client-creator
        restartPolicy: OnFailure
