FROM tomcat:8-jre8
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com>

RUN echo JAVA_OPTS='"-Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true -Dcom.squonk.keycloak.baseurl=$KEYCLOAK_SERVER_URL"' > /usr/local/tomcat/bin/setenv.sh
RUN rm -rf              /usr/local/tomcat/webapps/*

# copy the keycloak jars to the tomcat lib folder
COPY keycloak-jars-tomcat8/* /usr/local/tomcat/lib/

ADD portal/*.war        /usr/local/tomcat/webapps/
RUN unzip -d            /usr/local/tomcat/webapps/portal /usr/local/tomcat/webapps/ROOT.war && rm -f /usr/local/tomcat/webapps/ROOT.war

# remove unused or conflicting jars
RUN cd /usr/local/tomcat/webapps/portal/WEB-INF/lib && rm commons-codec-*.jar commons-logging-*.jar httpclient*.jar httpcore*.jar\
 keycloak*.jar jackson-annotations-*.jar jackson-core-*.jar jackson-databind-*.jar servlet-api-3.0.jar

 
EXPOSE 8080
