FROM tomcat:8.0-jre8
LABEL maintainer="Tim Dudgeon <tdudgeon@informaticsmatters.com>"

RUN echo JAVA_OPTS='"-Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true -Dcom.squonk.keycloak.baseurl=$KEYCLOAK_SERVER_URL"' > /usr/local/tomcat/bin/setenv.sh
RUN rm -rf              /usr/local/tomcat/webapps/*

# copy the keycloak jars to the tomcat lib folder
COPY keycloak-jars-tomcat8/* /usr/local/tomcat/lib/

ADD portal/*.war        /usr/local/tomcat/webapps/
RUN unzip -d            /usr/local/tomcat/webapps/portal /usr/local/tomcat/webapps/ROOT.war && rm -f /usr/local/tomcat/webapps/ROOT.war

# remove unused or conflicting jars
RUN cd /usr/local/tomcat/webapps/portal/WEB-INF/lib && rm commons-codec-*.jar commons-logging-*.jar httpclient*.jar httpcore*.jar\
 keycloak*.jar jackson-annotations-*.jar jackson-core-*.jar jackson-databind-*.jar servlet-api-3.0.jar

COPY portal/tomcat-users.xml /usr/local/tomcat/conf/
COPY portal/web.xml portal/beans.xml portal/persistence.properties /usr/local/tomcat/webapps/portal/WEB-INF/

# The following lines are a hack to work around a issue with mounting a ConfigMap with a speecified subPath.
# Create default content for the keycloak.json and context.xml files
RUN mkdir /tomcat-goodies && touch /tomcat-goodies/keycloak.json
COPY portal/context-empty.xml /tomcat-goodies/context.xml
# Copy the alterantive run command to the image
COPY portal/run.sh /usr/local/tomcat/bin/run-portal.sh

# Override the default run command with one that copies the files from /tomcat-goodies to their necessary locations
# and then execs the 'catalina.sh run' command
CMD ["run-portal.sh"]
