FROM tomcat:8.0-jre8
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com> 
# based on the hellyna/xwiki dockerhub image by Hellyna NG <hellyna@hellyna.com>

RUN rm -rf webapps/* &&\
 curl -L\
 'http://download.forge.ow2.org/xwiki/xwiki-enterprise-web-7.4.2.war'\
 -o xwiki.war &&\
 unzip -d webapps/xwiki xwiki.war &&\
 rm -f xwiki.war

RUN curl -L \
 'https://jdbc.postgresql.org/download/postgresql-9.4.1208.jar' \
 -o 'webapps/xwiki/WEB-INF/lib/postgresql-9.4.1208.jar'

COPY xwiki/setenv.sh bin/
COPY xwiki/catalina.policy.append catalina.policy.append

RUN cat catalina.policy.append >> conf/catalina.policy &&\
 rm catalina.policy.append &&\
 echo 'environment.permanentDirectory=/var/local/xwiki' >> webapps/xwiki/WEB-INF/xwiki.properties

# copy the keycloak configs to tomcat		
COPY ./keycloak-jars-tomcat8/* /usr/local/tomcat/lib/
# these two are provided by the Keycloak adapter in /usr/local/tomcat/lib
#RUN rm /usr/local/tomcat/webapps/xwiki/WEB-INF/lib/bcpix-jdk15on-* /usr/local/tomcat/webapps/xwiki/WEB-INF/lib/bcprov-jdk15on-*

COPY xwiki/context.xml /usr/local/tomcat/webapps/xwiki/META-INF/
COPY xwiki/web.xml /usr/local/tomcat/webapps/xwiki/WEB-INF/
COPY xwiki/xwiki.cfg /usr/local/tomcat/webapps/xwiki/WEB-INF/
COPY xwiki/hibernate.cfg.xml /usr/local/tomcat/webapps/xwiki/WEB-INF/
COPY xwiki/xwiki-authenticator-keycloak.jar /usr/local/tomcat/webapps/xwiki/WEB-INF/lib
COPY xwiki/server.xml /usr/local/tomcat/conf/server.xml

# change authenticator logging level (optional)
#RUN echo '\norg.keycloak.adapters.OAuthRequestAuthenticator.level = FINE\n' >> /usr/local/tomcat/conf/logging.properties

# change adapter logging level (optional)
#COPY xwiki/logback.xml /usr/local/tomcat/webapps/xwiki/WEB-INF/classes/

