# IMPORTANT NOTE
#
# This template is a just a 'shell' at the moment.
# It creates the cellexecutor service but the template
# is incomplete as a number of mounts and comms issues
# still need to be resolved. It is present here simply
# to act as the starting point for the finished article.

apiVersion: v1
kind: Template
metadata:
  name: cellexecutor
  annotations:
    description: "Squonk Cell Executor"
    iconClass: "icon-tomcat"
    tags: "squonk,cellexecutor"
labels:
  template: squonk-cellexecutor
  app: squonk-cellexecutor

message: "Squonk Cell Executor has been deployed."

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: cellexecutor
  spec:
    replicas: 1  
    selector:    
      name: cellexecutor
    template:    
      metadata:
        labels:  
          name: cellexecutor
      spec:
        containers:
        - image: squonk/cellexecutor
          name: cellexecutor
          env:
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_SQUONK_PASSWORD
          - name: DOCKER_HOST
            value: ${CELL_DOCKER_HOST}
          - name: JAVA_OPTS
            value: '"-Djava.util.logging.config.file=/logging.properties"'
          resources:
            limits:
              cpu: ${CELL_CPU_LIMIT}
              memory: ${CELL_MEM_LIMIT}
            requests:
              cpu: ${CELL_CPU_REQUEST}
              memory: ${CELL_MEM_REQUEST}
          volumeMounts:
          - mountPath: /squonk/work
            name: squonk-work
        volumes:
        - name: squonk-work
          emptyDir: {}

- apiVersion: v1
  kind: Service
  metadata:
    name: cellexecutor
  spec:
    selector:
      name: cellexecutor
    ports:
    - name: http
      port: 8080
      targetPort: 8080

parameters:

- name: CELL_DOCKER_HOST
  value: "unix:///var/run/docker.sock"

- name: CELL_CPU_REQUEST
  value: 500m
- name: CELL_CPU_LIMIT
  value: 1000m
- name: CELL_MEM_REQUEST
  value: 500Mi
- name: CELL_MEM_LIMIT
  value: 1Gi
