apiVersion: v1
kind: Template
metadata:
  name: service
  annotations:
    description: "Squonk Chemservices"
    iconClass: "icon-tomcat"
    tags: "chemservices"
labels:
  app: squonk-chemservices
  template: service
message: "Chemservices has been deployed."  

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
  spec:
    replicas: 1  
    selector:    
      name: ${APP_NAME}
    template:    
      metadata:
        labels:  
          name: ${APP_NAME}
      spec:
        containers:
        - image: squonk/chem-services-basic
          name: ${APP_NAME}
          env:
          - name: POSTGRES_SQUONK_PASSWORD
            value: ${POSTGRES_SQUONK_PASSWORD}
          - name: STRUCTURE_DATABASE_TABLES
            value: ${STRUCTURE_DATABASE_TABLES}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP	  
parameters:
- description: Application name
  name: APP_NAME
  value: chem-services-basic
- description: Postgres password for RDKit chemical search services
  name: POSTGRES_SQUONK_PASSWORD
  value: squonk
- description: Chemical search tables
  name: STRUCTURE_DATABASE_TABLES
  value: ""
