apiVersion: v1
kind: Template
metadata:
  name: chem-services-basic
  annotations:
    description: "Squonk Chemservices"
    iconClass: "icon-tomcat"
    tags: "squonk,chemservices"
labels:
  template: squonk-chemservices
  app: squonk-chemservices

message: "Squonk Chem Services have been deployed."

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: chem-services-basic
  spec:
    replicas: 1
    selector:
      name: chem-services-basic
    template:
      metadata:
        labels:
          name: chem-services-basic
      spec:
        containers:
        - image: squonk/chem-services-basic
          name: chem-services-basic
          env:
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: POSTGRES_SQUONK_PASSWORD
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_SQUONK_PASSWORD
          - name: STRUCTURE_DATABASE_TABLES
            value: ${STRUCTURE_DATABASE_TABLES}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEM_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEM_REQUEST}

- apiVersion: v1
  kind: Service
  metadata:
    name: chem-services-basic
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      name: chem-services-basic

parameters:

- name: STRUCTURE_DATABASE_TABLES
  description: Chemical search tables
  value: ""

- name: CPU_REQUEST
  value: 500m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 500Mi
- name: MEM_LIMIT
  value: 1Gi
