apiVersion: v1
kind: Template
metadata:
  name: squonk-chemservices
  annotations:
    description: "Squonk Chemservices"
    iconClass: "icon-tomcat"
    tags: "squonk,chemservices"
labels:
  template: squonk-chemservices

message: "Chemservices has been deployed."

objects:

- apiVersion: v1
  kind: DeploymentConfig
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_NAME}
    template:
      metadata:
        labels:  
          name: ${APP_NAME}
      spec:
        containers:
        - image: squonk/chem-services-basic
          name: ${APP_NAME}
          env:
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_SQUONK_PASSWORD
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: POSTGRES_SQUONK_PASSWORD
          - name: STRUCTURE_DATABASE_TABLES
            value: ${STRUCTURE_DATABASE_TABLES}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /chem-services-cdk-basic/rest/ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
        restartPolicy: Always

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP

parameters:

- name: APP_NAME
  value: squonk-chemservices

- name: STRUCTURE_DATABASE_TABLES
  description: Chemical search tables
  value: ""

- name: CPU_REQUEST
  value: 500m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 500Mi
- name: MEM_LIMIT
  value: 1Gi
