# oc process -f portal.yaml | oc create -f -
# oc delete all --selector template=squonk-portal

apiVersion: v1
kind: Template
metadata:
  name: cellexecutor
  annotations:
    description: "Squonk Portal"
    iconClass: "icon-tomcat"
    tags: "squonk,portal"
labels:
  template: squonk-portal
  app: squonk-portal

message: "Squonk Portal has been deployed."

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: portal
  spec:
    replicas: 1
    selector:
      name: portal
    template:
      metadata:
        labels:
          name: portal
      spec:
        initContainers:
        - image: busybox
          name: init-postgres
          command: ['sh', '-c',
            'until nslookup coreservices; do sleep 4; done;']
        containers:
        - image: squonk/portal
          name: portal
          env:
          - name: POSTGRES_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: POSTGRES_SQUONK_PASSWORD
          - name: SERVICE_CALLBACK
            value: ${PORTAL_SERVICE_CALLBACK}
          readinessProbe:
            httpGet:
              path: /portal
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /portal
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
#          resources:
#            limits:
#              cpu: ${PORTAL_CPU_LIMIT}
#              memory: ${PORTAL_MEM_LIMIT}
#            requests:
#              cpu: ${PORTAL_CPU_REQUEST}
#              memory: ${PORTAL_MEM_REQUEST}

- apiVersion: v1
  kind: Service
  metadata:
    name: portal
  spec:
    selector:
      name: portal
    ports:
    - name: http
      port: 8080
      targetPort: 8080

parameters:

- name: PORTAL_SERVICE_CALLBACK
  value: "http://localhost:8080/portal"

- name: PORTAL_CPU_REQUEST
  value: 500m
- name: PORTAL_CPU_LIMIT
  value: 1000m
- name: PORTAL_MEM_REQUEST
  value: 500Mi
- name: PORTAL_MEM_LIMIT
  value: 1Gi
