apiVersion: v1
kind: Template
metadata:
  name: squonk-rabbitmq
  annotations:
    description: "Squonk RabbitMQ"
    iconClass: "icon-tomcat"
    tags: "squonk,rabbitmq"
labels:
  template: squonk-rabbitmq

message: "RabbitMQ has been deployed."  

# Note (abc:10th Oct)
# This service needs a 'poke' ATM.
# Once started the 'only once' script
# (/squonk-rabbitmq-setup/rabbitmq-setup.sh) needs to be run.
#
# From a terminal...
#
# cd /squonk-rabbitmq-setup
# bash rabbitmq-setup.sh
#
# You can ignore the two errors about the unknonw guest and squonk users

objects:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: squonk-rabbitmq-setup
    labels:
      app: ${APP_NAME}
  data:
    rabbitmq-setup.sh: |-
      #!/bin/bash
      rabbitmqctl delete_user guest
      rabbitmqctl delete_user squonk
      rabbitmqctl add_vhost /squonk
      echo "  created /squonk virtualhost"
      rabbitmqctl add_user squonk ${RABBITMQ_SQUONK_PASSWORD:-squonk}
      echo "  created squonk user with password ${RABBITMQ_SQUONK_PASSWORD:-squonk}"
      rabbitmqctl change_password admin ${RABBITMQ_DEFAULT_PASSWORD:-squonk}
      echo "  admin password set to ${RABBITMQ_DEFAULT_PASSWORD:-squonk}"
      rabbitmqctl set_permissions -p /       admin  '.*' '.*' '.*'
      rabbitmqctl set_permissions -p /squonk admin  '.*' '.*' '.*'
      rabbitmqctl set_permissions -p /squonk squonk '.*' '.*' '.*'
      echo "  rabbitmq setup complete"
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rabbitmq
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1  
    selector:    
      name: rabbitmq
    template:    
      metadata:
        labels:  
          name: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_PASS
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_ERLANG_COOKIE
          ports:
          - containerPort: 15672
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEM_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEM_REQUEST}
            privileged: false
          volumeMounts:
          - name: squonk-rabbitmq-setup
            mountPath: /squonk-rabbitmq-setup
        volumes:
        - name: squonk-rabbitmq-setup
          configMap:
            name: squonk-rabbitmq-setup
        restartPolicy: Always
        
- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672
    selector:
      name: rabbitmq
    sessionAffinity: None
    type: ClusterIP

parameters:

- name: APP_NAME
  value: "squonk-rabbitmq"

- name: CPU_REQUEST
  value: 500m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 500Mi
- name: MEM_LIMIT
  value: 1Gi
