apiVersion: v1
kind: Template
metadata:
  name: squonk-rabbitmq
  annotations:
    description: "Squonk RabbitMQ"
    iconClass: "icon-tomcat"
    tags: "squonk,rabbitmq"
labels:
  template: squonk-rabbitmq
  app: squonk-rabbitmq

message: "RabbitMQ has been deployed."  

objects:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: squonk-rabbitmq-config
  data:
    rabbitmq.config: |
      [
        {rabbit, [
          {loopback_users, []}
        ]},
        {rabbitmq_management, [
          {load_definitions, "/etc/rabbitmq-squonk/definitions.json"}
        ]}
      ].
    definitions.json: |
      {
        "rabbit_version": "3.6.12",
        "users": [
          {
            "name": "squonk",
            "password": "squonk",
            "tags": ""
          },
          {
            "name": "admin",
            "password": "squonk",
            "tags": ""
          }
        ],
        "vhosts": [
          {
            "name": "\/"
          },
          {
            "name": "\/squonk"
          }
        ],
        "permissions": [
          {
            "user": "squonk",
            "vhost": "\/squonk",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "admin",
            "vhost": "\/squonk",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "admin",
            "vhost": "\/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "parameters": [],
        "policies": [],
        "queues": [],
        "exchanges": [],
        "bindings": []
      }
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rabbitmq
  spec:
    replicas: 1  
    selector:    
      name: rabbitmq
    template:    
      metadata:
        labels:  
          name: rabbitmq
      spec:
        containers:
        - image: rabbitmq:${RABBITMQ_TAG}
          name: rabbitmq
          env:
          - name: RABBITMQ_CONFIG_FILE
            value: ${RABBITMQ_CONFIG_FILE}
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_PASS
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_ERLANG_COOKIE
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_SQUONK_PASSWORD
          ports:
          - containerPort: 5672
          - containerPort: 15672
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEM_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEM_REQUEST}
          volumeMounts:
          - name: squonk-rabbitmq-config
            mountPath: /etc/rabbitmq-squonk
        volumes:
        - name: squonk-rabbitmq-config
          configMap:
            name: squonk-rabbitmq-config

- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
  spec:
    ports:
    - name: ampq
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
    selector:
      name: rabbitmq

parameters:

- name: RABBITMQ_TAG
  value: "3.6.12-management"
  description: The version tag for the RabbitMQ container

- name: RABBITMQ_CONFIG_FILE
  value: /etc/rabbitmq-squonk/rabbitmq
  description: >
    The path to the configuration file, without the .config extension.
    We mount this directory in the container and add the
    configuration files using our ConfigMap.

- name: CPU_REQUEST
  value: 500m
- name: CPU_LIMIT
  value: 1000m
- name: MEM_REQUEST
  value: 500Mi
- name: MEM_LIMIT
  value: 1Gi
