apiVersion: v1
kind: Template
metadata:
  name: squonk-secrets
  annotations:
    description: "Squonk secrets"
    tags: "squonk,secrets"
labels:
  template: squonk-secrets

message: "Secrets have been deployed."

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  stringData:
    POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    POSTGRES_SQUONK_PASSWORD: ${POSTGRES_SQUONK_PASSWORD}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_XWIKI_PASSWORD: ${POSTGRES_XWIKI_PASSWORD}
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}

parameters:

- name: APP_NAME
  value: squonk-secrets

- name: POSTGRES_KEYCLOAK_PASSWORD
  value: squonk
- name: POSTGRES_SQUONK_PASSWORD
  value: squonk
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_XWIKI_PASSWORD
  value: squonk

- name: RABBITMQ_DEFAULT_USER
  value: admin
- name: RABBITMQ_DEFAULT_PASS
  value: squonk
- name: RABBITMQ_SQUONK_PASSWORD
  value: squonk
- name: RABBITMQ_ERLANG_COOKIE
  description: RabbitMQ Erlang cookie
  from: '[a-zA-Z0-9]{12}'
  generate: expression 
