apiVersion: v1
kind: Template
metadata:
  name: squonk-secrets
  annotations:
    description: "Squonk secrets"
    tags: "squonk,secrets"
labels:
  template: squonk-secrets

message: "Secrets have been deployed."

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  stringData:
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    POSTGRES_SQUONK_PASSWORD: ${POSTGRES_SQUONK_PASSWORD}
      
parameters:

- name: APP_NAME
  value: squonk-secrets

- description: Postgres password for squonk user
  name: POSTGRES_SQUONK_PASSWORD
  value: squonk
- description: RabbitMQ admin username
  name: RABBITMQ_DEFAULT_USER
  value: admin
- description: RabbitMQ admin password
  name: RABBITMQ_DEFAULT_PASS
  value: squonk
- description: RabbitMQ Erlang cookie
  name: RABBITMQ_ERLANG_COOKIE
  from: '[a-zA-Z0-9]{12}'
  generate: expression 
