# oc process -f squonk-secrets.yaml | oc create -f -
# oc delete secrets --selector template=squonk-secrets

kind: Template
apiVersion: v1
metadata:
  name: squonk-secrets
  annotations:
    description: Squonk Secrets Definition
    tags: squonk,secrets
labels:
  template: squonk-secrets
  app: squonk-secrets

parameters:

# -------------
# Configuration
# -------------

- name: SECRETS_NAMESPACE
  value: squonk

# --------
# Secrets
# --------

- name: KEYCLOAK_USER
  value: admin
- name: KEYCLOAK_PASSWORD
  value: squonk

- name: POSTGRES_KEYCLOAK_PASSWORD
  value: squonk
- name: POSTGRES_SQUONK_PASSWORD
  value: squonk
- name: POSTGRES_PASSWORD
  value: postgres
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_XWIKI_PASSWORD
  value: squonk

- name: RABBITMQ_DEFAULT_USER
  value: admin
- name: RABBITMQ_DEFAULT_PASS
  value: squonk
- name: RABBITMQ_ERLANG_COOKIE
  description: RabbitMQ Erlang cookie
  from: '[a-zA-Z0-9]{12}'
  generate: expression
- name: RABBITMQ_SQUONK_PASSWORD
  value: squonk

objects:

# -----------------------------------------------------------------------------
# Secrets
# -----------------------------------------------------------------------------

- kind: Secret
  apiVersion: v1
  metadata:
    name: squonk-secrets
    namespace: ${SECRETS_NAMESPACE}
  stringData:
    KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    KEYCLOAK_USER: ${KEYCLOAK_USER}

    POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    POSTGRES_SQUONK_PASSWORD: ${POSTGRES_SQUONK_PASSWORD}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_XWIKI_PASSWORD: ${POSTGRES_XWIKI_PASSWORD}

    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    RABBITMQ_SQUONK_PASSWORD: ${RABBITMQ_SQUONK_PASSWORD}
