# (oc adm policy add-scc-to-group anyuid system:authenticated)
#
# oc process -f squonk-infra-openshift.yaml | oc create -f -
# oc delete all,cm,pvc,secrets --selector template=squonk-infra

kind: Template
apiVersion: v1
metadata:
  name: squonk-infra
  annotations:
    description: Squonk Infrastructure Service Definition
    tags: squonk,infratsrtucture,postgres,rabbitmq
labels:
  template: squonk-infra
  app: squonk-infra

parameters:

# -------------
# Configuration
# -------------
# Common (not specific to any infrastructure service)

- name: INFRA_NAMESPACE
  value: squonk


# --------
# RabbitMQ
# --------

- name: RABBITMQ_IMAGE_TAG
  value: 3.6.12-management
  description: The version tag for the RabbitMQ container

- name: RABBITMQ_CONFIG_FILE
  value: /etc/rabbitmq-squonk/rabbitmq
  description: >
    The path to the configuration file, without the .config extension.
    We mount this directory in the container and add the
    configuration files using our ConfigMap.

- name: RABBITMQ_CPU_REQUEST
  value: 100m
- name: RABBITMQ_CPU_LIMIT
  value: 1000m
- name: RABBITMQ_MEM_REQUEST
  value: 100Mi
- name: RABBITMQ_MEM_LIMIT
  value: 500Mi

objects:

# -----------------------------------------------------------------------------
# RabbitMQ Service
# -----------------------------------------------------------------------------

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-rabbitmq-config
    namespace: ${INFRA_NAMESPACE}
  data:
    rabbitmq.config: |
      [
        {rabbit, [
          {loopback_users, []}
        ]},
        {rabbitmq_management, [
          {load_definitions, "/etc/rabbitmq-squonk/definitions.json"}
        ]}
      ].
    definitions.json: |
      {
        "rabbit_version": "3.6.12",
        "users": [
          {
            "name": "squonk",
            "password": "squonk",
            "tags": ""
          },
          {
            "name": "admin",
            "password": "squonk",
            "tags": ""
          }
        ],
        "vhosts": [
          {
            "name": "\/"
          },
          {
            "name": "\/squonk"
          }
        ],
        "permissions": [
          {
            "user": "squonk",
            "vhost": "\/squonk",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "admin",
            "vhost": "\/squonk",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "admin",
            "vhost": "\/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "parameters": [],
        "policies": [],
        "queues": [],
        "exchanges": [],
        "bindings": []
      }

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: rabbitmq
    namespace: ${INFRA_NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: rabbitmq
    template:
      metadata:
        labels:
          name: rabbitmq
      spec:
        containers:
        - image: rabbitmq:${RABBITMQ_IMAGE_TAG}
          name: rabbitmq
          env:
          - name: RABBITMQ_CONFIG_FILE
            value: ${RABBITMQ_CONFIG_FILE}
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_DEFAULT_PASS
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_ERLANG_COOKIE
          - name: RABBITMQ_SQUONK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: squonk-secrets
                key: RABBITMQ_SQUONK_PASSWORD
          ports:
          - containerPort: 5672
          - containerPort: 15672
#          resources:
#            limits:
#              cpu: ${RABBITMQ_CPU_LIMIT}
#              memory: ${RABBITMQ_MEM_LIMIT}
#            requests:
#              cpu: ${RABBITMQ_CPU_REQUEST}
#              memory: ${RABBITMQ_MEM_REQUEST}
          volumeMounts:
          - name: squonk-rabbitmq-config
            mountPath: /etc/rabbitmq-squonk
        volumes:
        - name: squonk-rabbitmq-config
          configMap:
            name: squonk-rabbitmq-config

- kind: Service
  apiVersion: v1
  metadata:
    name: rabbitmq
    namespace: ${INFRA_NAMESPACE}
  spec:
    ports:
    - name: ampq
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
    selector:
      name: rabbitmq
