---
kind: Template
apiVersion: v1
metadata:
  name: db-prepare
labels:
  template: db-prepare
message: 'Squonk DB created.'

parameters:

- displayName: Squonk user password
  description: Squonk user password
  name: SQUONK_USER_PASSWORD
  from: "[a-zA-Z0-9]{10}"
  generate: expression
  required: true

- displayName: Squonk namespace (Project)
  description: Squonk namespace (Project)
  name: SQUONK_NAMESPACE
  value: squonk

- displayName: Postgres Admin user
  description: Postgres Admin user
  name: POSTGRESQL_ADMIN_USER

- displayName: Postgres Admin password
  description: Postgres Admin password
  name: POSTGRESQL_ADMIN_PASSWORD

objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: squonk-database-credentials
    namespace: ${SQUONK_NAMESPACE}
  stringData:
    user-password: ${SQUONK_USER_PASSWORD}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: squonk-database-creator
  data:
    init-squonk-db.sh: |
      #!/bin/bash

      export PGUSER=${POSTGRESQL_ADMIN_USER:-postgres}
      export PGPASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
      export PGHOST=${POSTGRESQL_HOST:-postgres}

      psql --command "CREATE USER squonk WITH PASSWORD '${SQUONK_USER_PASSWORD}'"
      echo "Created users"

      createdb -O squonk squonk
      echo "Created database"

      psql --command "GRANT CONNECT ON DATABASE squonk to squonk"
      psql -d squonk --command "DROP SCHEMA public CASCADE"
      psql -d squonk --command "CREATE SCHEMA users AUTHORIZATION squonk"
      psql -d squonk --command "GRANT USAGE ON SCHEMA users TO squonk"

      
      echo "Setup complete"

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: squonk-database-creator
  spec:
    template:
      metadata:
        name: squonk-database-creator
      spec:
        volumes:
        - name: squonk-database-creator
          configMap:
            name: squonk-database-creator
        containers:
        - name: squonk-database-creator
          env:
          - name: POSTGRESQL_ADMIN_USER
            value: ${POSTGRESQL_ADMIN_USER}
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: ${POSTGRESQL_ADMIN_PASSWORD}
          - name: SQUONK_USER_PASSWORD
            value: ${SQUONK_USER_PASSWORD}
          - name: POSTGRESQL_HOST
            value: postgresql.openrisknet-infra.svc
          image: centos/postgresql-95-centos7
          command:
          - /bin/bash
          - /create-db/init-squonk-db.sh
          volumeMounts:
          - mountPath: /create-db
            name: squonk-database-creator
        restartPolicy: Never
