version: '2.1'

networks:
    squonk_back:
        driver: bridge  
    squonk_isolated:
        driver: bridge
services:

    postgres:
        image: informaticsmatters/rdkit_cartridge:Release_2016_03_1
        volumes:
        - ./deploy/images/postgres/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck.sh
        - ./deploy/images/postgres/init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh:ro
        ports: 
        - "5432:5432"
        environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
        networks:
        - squonk_back
        healthcheck:
            test: docker-healthcheck.sh
            interval: 5s
            timeout: 2s
            retries: 10 


    rabbitmq:
        image: rabbitmq:3-management
        ports:
        - "5672:5672"
        - "15672:15672"
        volumes:
        - ./deploy/images/rabbitmq/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck.sh
        - "./rabbitmq/clean.sh:/usr/local/etc/clean.sh:ro"
        environment: 
            RABBITMQ_ERLANG_COOKIE: topsecret
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: squonk
        networks:
        - squonk_back
        healthcheck:
            test: docker-healthcheck.sh
            interval: 5s
            timeout: 2s
            retries: 10
            
    stage1:
        image: busybox
        networks:
         - squonk_isolated
         - squonk_back
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy

    # coreserives sometimes fails to start because chemservices is too slow to start. If this happens increase the number of retries in the healthcheck
    chemservices:
        image: squonk/chemservices-basic:latest
        ports:
        - "8092:8080"
        volumes:
        - ./deploy/images/chemservices/chemaxon_reaction_library.zip:/chemaxon_reaction_library.zip:ro
        networks:
        - squonk_back
        healthcheck:
            test: curl --fail http://localhost:8080/chem-services-cdk-basic/rest/ping || exit 1
            interval: 10s
            timeout: 5s
            retries: 10

    coreservices:
        image: squonk/coreservices:latest
        ports:
        - 8091:8080
        volumes:
        - ./docker-services:/var/local/squonk-docker-services
        depends_on:
            postgres:
                condition: service_started
            rabbitmq:
                condition: service_started
            chemservices:
                condition: service_healthy
        environment:
            SQUONK_BASIC_CHEM_SERVICES_URL: "http://chemservices:8080" # internal port
            SQUONK_DOCKER_SERVICES_DIR: "/var/local/squonk-docker-services"
        networks:
        - squonk_back
        healthcheck:
            test: curl --fail http://localhost:8080/coreservices/rest/ping || exit 1
            interval: 20s
            timeout: 5s
            retries: 3

    cellexecutor:
        image: squonk/cellexecutor:latest
        depends_on:
        - coreservices
        - rabbitmq
        - chemservices
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /squonk/work:/squonk/work:Z
        - /var/maven_repo:ro,Z
        security_opt:
        - label:disable # disable SELinux so that we can access docker.sock
        environment:
            DOCKER_HOST: unix:///var/run/docker.sock
            SQUONK_DOCKER_WORK_DIR: /squonk/work/docker
            SQUONK_DEBUG_MODE:
            ISOLATED_NETWORK_NAME: docker_squonk_isolated
            registry.url: https://index.docker.io/v1/
        networks:
        - squonk_back
            
    stage2:
        image: busybox
        networks:
        - squonk_back
        depends_on:
            coreservices:
                condition: service_healthy


