---

# The OpenShift Job definition for the Squonk Pipelines SD-Loader image.

kind: Template
apiVersion: v1
metadata:
  name: pipelines-sd-poster
labels:
  template: pipelines-sd-poster

parameters:

- name: POSTER_IMAGE
  value: squonk/rdkit-pipelines-sdposter
- name: POSTER_IMAGE_TAG
  value: latest
- name: POSTER_SA
  value: squonk
- name: POSTER_JOB_NAME
  value: pipelines

- name: PULL_POLICY
  value: Always

objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${POSTER_JOB_NAME}
  spec:
    template:
      spec:
        serviceAccountName: ${POSTER_SA}

        initContainers:
        - image: yauritux/busybox-curl
          name: wait-for-core-before-pipelines-post
          command: ['sh', '-c',
            'until (( curl http://coreservices:8080/rest/ping --connect-timeout 5 )); do sleep 2; done']

        containers:
        - image: ${POSTER_IMAGE}:${POSTER_IMAGE_TAG}
          name: ${POSTER_JOB_NAME}
          imagePullPolicy: ${PULL_POLICY}

        restartPolicy: Never
