---

# The Infrastructure Persistant storage using dynamic provisioning.
# With dynamic provisioning you only need to provide the PVC and specify
# the storage class.
#
# oc process -f infra-pvc-dynamic.yaml | oc create -f -
# oc delete pvc --selector template=infra-pvc-dynamic

kind: Template
apiVersion: v1
metadata:
  name: chemcentral-persistence-dynamic
  annotations:
    description: Chemcentral database persistence using dynamic provisioning
    tags: squonk,chemcentral,pv,pvc
labels:
  template: chemcentral-pvc-dynamic

parameters:

- name: NAMESPACE
  value: chemcentral

- name: STORAGE_CLASS
  value: standard

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: chemcentral-postgresql-claim
    namespace: ${NAMESPACE}
    labels:
      application: chemcentral
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"
    storageClassName: ${STORAGE_CLASS}


