---

# The user has created a MiniShift instance
#
# Here, we create an 'admin' user
# then assign Cluster Admin role to it,
# it's what's expected of the downstream plays.

- name: Login as MiniShift system:admin
  shell: oc login -u system:admin
  changed_when: False

- name: Check admin user
  shell: oc get users
  register: users_result
  changed_when: False

- name: Create admin user
  shell: oc create user {{ oc_admin }}
  when: not users_result.stdout | regex_search('^%s\s' % oc_admin, multiline=True)

- name: Check cluster-admin Roles
  shell: oc get clusterrolebindings | grep cluster-admin
  register: role_result
  changed_when: False

- name: Assigning cluster-admin to admin user
  shell: oc adm policy add-cluster-role-to-user cluster-admin {{ oc_admin }}
  when: not role_result.stdout | regex_search('^\S+\s+\S+\s+%s' % oc_admin, multiline=True)
