---

# Patches Minishift volumes by setting w/r/x permissions globally.
# This is often used to get postgres running in MiniShift we
# set permissions on the PV that is used.
#
# Variables:
#
#   claim: The PVC name for the volume to be patched

# The path to the PV changes
# when we get to MiniShift v1.26.0

- import_tasks: get-version.yaml

- name: Get PVC
  shell: oc get pvc/{{ claim }} --no-headers | tr -s ' ' | cut -f 3 -d ' '
  register: pg_pvc_result
  changed_when: False

- name: Adjust PVC permissions (pre v1.26)
  shell: >
    minishift ssh -- sudo chmod 777
    /mnt/sda1/var/lib/minishift/openshift.local.pv/{{ pg_pvc_result.stdout }}
  when: minishift_version is version('1.26.0', '<')
  changed_when: False

- name: Adjust PVC permissions (post v1.25)
  shell: >
    minishift ssh -- sudo chmod 777
    /mnt/sda1/var/lib/minishift/base/openshift.local.pv/{{ pg_pvc_result.stdout }}
  when: minishift_version is version('1.26.0', '>=')
  changed_when: False
