/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'timbo' at '23/02/15 15:20' with Gradle 2.2.1
 *
 * @author timbo, @date 23/02/15 15:20
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
