---

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Infrastructure claims

- name: Check Infrastructure PVCs (dyanmic)
  shell: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Infrastructure PVCs (dynamic)
  shell: >
    oc process
    -p STORAGE_CLASS={{ oc_infra_volume_storage_class }}
    -p POSTGRESQL_VOLUME_SIZE={{ oc_postgresql_volume_size }}
    -p RABBITMQ_VOLUME_SIZE={{ rabbitmq_volume_size }}
    -f {{ role_path }}/{{ t_dir }}/squonk-infra/infra-pvc-dynamic.yaml
    | oc create -f -
  when: not i_pvc_result.stdout | regex_search('^rabbitmq-claim\s', multiline=True)

- name: Wait for PVCs to become Bound (dynamic)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  delay: 5
  retries: "{{ (pvc_bind_timeout | int / 5) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - postgresql-claim
  - rabbitmq-claim
  when: not i_pvc_result.stdout | regex_search('^rabbitmq-claim\s', multiline=True)

# Backup claims

- name: Create Backup PVCs (dynamic)
  shell: >
    oc process
    -p POSTGRESQL_BACKUP_VOLUME_SIZE={{ oc_infra_backup_volume_size }}
    -f {{ role_path }}/{{ t_dir }}/squonk-infra/infra-backup-pvc-dynamic.yaml
    | oc create -f -
  when:
  - not i_pvc_result.stdout | regex_search('^postgresql-backup-claim\s', multiline=True)
  - oc_infra_backup_hourly_count > 0

- name: Wait for Backup PVCs to become Bound (dynamic)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  delay: 5
  retries: "{{ (pvc_bind_timeout | int / 5) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - postgresql-backup-claim
  when:
  - not i_pvc_result.stdout | regex_search('^rabbitmq-claim\s', multiline=True)
  - oc_infra_backup_hourly_count > 0
