---

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Check SA
  shell: oc get sa
  register: sa_result
  changed_when: False

- name: Create SA
  shell: "{{ item }}"
  loop:
  - oc create sa {{ oc_infra_sa }}
  when: not sa_result.stdout | regex_search('^%s\s' % oc_infra_sa, multiline=True)
