---

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}

# Create PVs and PVCs
# The PV and PVC definitions are combined in one template file.

- name: Check Infrastructure PV/PVC
  shell: oc get pv
  register: i_pv_result

- name: Create Infrastructure PV/PVC
  shell: >
    oc process
    -p INFRA_NAMESPACE={{ oc_infra_project }}
    -p NFS_SERVER={{ oc_nfs_server }}
    -p NFS_PATH={{ oc_nfs_path }}
    -f {{ role_path }}/{{ t_dir }}/squonk-infra/infra-pvc-nfs.yaml
    | oc create -f -
  when: '"pv-rabbitmq" not in i_pv_result.stdout'
