---

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Check Keycloak Deployment
  shell: oc get dc
  register: sso_dc_result
  changed_when: False

- name: Create Keycloak Deployment
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-infra/sso-postgres.yaml
    -p SSO_REALM={{ keycloak_realm }}
    -p POSTGRESQL_SHARED_BUFFERS={{ postgresql_shared_buffer_size }}
    -p HOSTNAME_HTTPS=sso.{{ oc_routes_basename }}
    | oc create -f -
  when: '"db-postgresql" not in sso_dc_result.stdout'

# Wait for running pods

- name: Wait for PostgreSQL
  shell: oc get po | grep db-postgresql | grep -v deploy | grep 1/1 > /dev/null
  retries: 15
  delay: 20
  register: result
  until: result.rc == 0
  when: wait_for_pods
  changed_when: False

- name: Wait for Keycloak
  shell: oc get po | grep sso | grep -v deploy | grep 1/1 > /dev/null
  retries: 10
  delay: 30
  register: result
  until: result.rc == 0
  when: wait_for_pods
  changed_when: False

# Deploy backups

- name: Deploy Backup CronJobs
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/squonk-infra/sso-backup.yaml
    | oc create -f -
  when: oc_infra_deploy_backup
