#!/usr/bin/env bash

echo "=-> Assembling..."

echo "ls -la /tmp"
ls -la /tmp
echo "ls -la /tmp/artifacts"
ls -la /tmp/artifacts
echo "ls -la /tmp/artifacts/cache"
ls -la /tmp/artifacts/cache
echo "ls -la /tmp/artifacts/cache/.gradle"
ls -la /tmp/artifacts/cache/.gradle
echo "ls -la /tmp/src"
ls -la /tmp/src
echo "ls -la /tmp/cache"
ls -la /tmp/cache

echo "echo HOME"
echo ${HOME}

if [ -d /tmp/artifacts/cache ]; then
    echo "=-> Restoring cache directory from incremental build."
    ls -la /tmp/artifacts/cache
    mkdir -p ${HOME}/.gradle
    cp -r /tmp/artifacts/cache/.gradle ${HOME}/.gradle/
fi

echo "ls -la HOME"
ls -la ${HOME}

# Build the application and its artifacts.
# S2I places the root of the 'source'
# (the squonk git repo in our case)
# in /tmp/src
echo "=-> Building..."
pushd ${HOME}
cd /tmp/src/components
gradle build --build-cache --no-daemon -x test
popd

# For incremental builds we move key build files
# to the /home/squonk/cache directory
#
# https://medium.com/cirruslabs/mastering-gradle-caching-and-incremental-builds-37eb1af7fcde
echo "=-> Cleaning artifacts..."
rm -rf ${HOME}/.gradle/caches/3.5.1/
find ${HOME}/.gradle/caches/ -name "*.lock" -type f -delete

echo "=-> Copying artifacts to cache..."
mkdir -p /tmp/cache
cp -r ${HOME}/.gradle /tmp/cache/
ls -la /tmp/cache

echo "=-> Assembled"
