---

- hosts: localhost
  vars_files:
  - ../../../env/{{ ansible_env.IM_PARAMETER_FILE }}

  tasks:
  - name: Create the Loader (Data) Volume
    include_role:
      name: squonk-chemcentral
      tasks_from: create-loader-volume.yaml
