---

- hosts: localhost
  vars_files:
  - ../../../env/{{ ansible_env.IM_PARAMETER_FILE }}

  tasks:

  - name: Run the Loader Preparation Tasks
    include_role:
      name: squonk-chemcentral
      tasks_from: create-loader-volume.yaml

  - name: Run the Loader Preparation Tasks
    include_role:
      name: squonk-chemcentral
      tasks_from: prep-loader-emolecules.yaml
