---

- hosts: localhost
  vars_files:
  - ../../../env/{{ ansible_env.IM_PARAMETER_FILE }}

  tasks:
  - name: Run the Squonk ChemCentral Undeploy Tasks
    include_role:
      name: squonk-chemcentral
      tasks_from: undeploy.yaml
