FROM rabbitmq:3-management
LABEL maintainer="Tim Dudgeon <tdudgeon@informaticsmatters.com>"

COPY ./init.sh /usr/local/etc/
COPY ./update-credentials.sh /usr/local/etc/
COPY ./clean.sh /usr/local/etc/


