/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'timbo' at '19/02/15 13:05' with Gradle 2.2.1
 *
 * @author timbo, @date 19/02/15 13:05
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
