---

# Preparation and project creation for ChemCentral Search.

- name: Login (user) ({{ oc_master_url }})
  command: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

# ChemCentral Search Project

- name: Check the Project
  command: oc get projects
  register: projects_result
  changed_when: False

- name: Create the ChemCentral Search Project
  command: >
    oc new-project {{ oc_cc_project }} --display-name='{{ oc_cc_project_display_name }}'
  when: >
    not projects_result.stdout
    | regex_search('^%s\s' % oc_cc_project, multiline=True)
