---

# Infrastructure claims

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Check Infrastructure PVCs (minishift)
  shell: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Infrastructure PVCs (minishift)
  shell: >
    oc process
    -p POSTGRESQL_VOLUME_SIZE={{ oc_cc_postgresql_volume_size }}
    -f {{ role_path }}/files/chemcentral-pvc-minishift.yaml
    | oc create -f -
  when: not i_pvc_result.stdout | regex_search('^chemcentral-postgresql-claim\s', multiline=True)

# Wait for claims to become bound...

- name: Wait for Infrastructure PVCs to become Bound (minishift)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  delay: 15
  retries: "{{ (pvc_bind_timeout | int / 15) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - chemcentral-postgresql-claim
  when: not i_pvc_result.stdout | regex_search('^chemcentral-postgresql-claim\s', multiline=True)

# Squonk claims

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False

- name: Check Squonk PVCs (minishift)
  shell: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Squonk PVCs (minishift)
  shell: >
    oc process
    -f {{ role_path }}/files/chemcentral-data-loader-pvc-minishift.yaml
    | oc create -f -
  when: not i_pvc_result.stdout | regex_search('^chemcentral-data-loader-pvc\s', multiline=True)

# Wait for claims to become bound...

- name: Wait for Squonk PVCs to become Bound (minishift)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  delay: 15
  retries: "{{ (pvc_bind_timeout | int / 15) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - chemcentral-data-loader-pvc
  when: not i_pvc_result.stdout | regex_search('^chemcentral-data-loader-pvc\s', multiline=True)

