---

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Check/Create PVs

- name: Check Infrastructure PVs
  shell: oc get pv
  register: i_pv_result
  changed_when: False

- name: Create Infrastructure PVs
  shell: >
    oc process
    -p INFRA_NAMESPACE={{ oc_infra_project }}
    -p NFS_SERVER={{ ansible_env.OC_NFS_SERVER }}
    -p NFS_PATH={{ ansible_env.OC_NFS_PATH }}
    -f {{ role_path }}/{{ t_dir }}/chemcentral/chemcentral-pv-nfs.yaml
    | oc create -f -
  when: not i_pv_result.stdout | regex_search('^%s\s' % pv_name, multiline=True)

# Wait for PVs to become "Available"...

- name: Wait for PVs to become Available
  shell: >
    oc get pv/{{ item }} | grep Available
  retries: 6
  delay: 5
  register: result
  until: result.rc == 0
  loop:
  - "{{ pv_name }}"
  when: not i_pv_result.stdout | regex_search('^%s\s' % item, multiline=True)

# Deal with "Released" volumes.
# Those PVs that are "Released"
# must be "Available" to accept new binds...

- name: Check Released volumnes
  shell: oc get pv | grep Released | grep {{ oc_infra_project }}/ | cut -f 1 -d " "
  register: released_vols
  when: recycle_released_pvs

- name: Recover Released volumes
  shell: >
    oc patch pv/{{ item }} --type json
    -p $'- op: remove\n  path: /spec/claimRef'
  with_items:
  - "{{ released_vols.stdout_lines }}"
  when: recycle_released_pvs

# Check/Create PVCs

- name: Check Infrastructure PVCs (nfs)
  shell: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Infrastructure PVCs (nfs)
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/chemcentral/chemcentral-pvc-nfs.yaml
    | oc create -f -
  when: not i_pvc_result.stdout | regex_search('^%s\s' % pvc_name, multiline=True)

# Wait for PVCs to become "Bound"...

- name: Wait for PVCs to become Bound (nfs)
  shell: >
    oc get pvc/{{ item }} | grep Bound
  retries: 6
  delay: 5
  register: result
  until: result.rc == 0
  loop:
  - "{{ pvc_name }}"
  when: not i_pvc_result.stdout | regex_search('^%s\s' % pvc_name, multiline=True)
