---

- name: Login (admin) ({{ oc_master_url }})
  command: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to ChemCentral Search Project
  command: oc project {{ oc_cc_project }}
  changed_when: False

- name: Check SA
  command: oc get sa
  register: sa_result
  changed_when: False

- name: Create SA
  command: oc create sa {{ oc_cc_sa }}
  when: not sa_result.stdout|regex_search('^%s\s' % oc_cc_sa, multiline=True)

- name: Check Security Context Constraints
  command: oc describe scc anyuid
  register: scc_result
  changed_when: False

- name: Set Roles
  command: "{{ item }}"
  loop:
  - oc adm policy add-scc-to-user anyuid -z {{ oc_cc_sa }}
  when: >-
    not scc_result.stdout
    | regex_search('^\s+Users:\s+\S*:%s:%s' % (oc_cc_project, oc_cc_sa), multiline=True)
