---

# Create the ChemCentral service account in the infrastructure project.

- name: Login (admin)
  shell: oc login {{ oc_master_hostname }} -u admin -p {{ oc_admin_password }}
  changed_when: False

- name: Check SA (Infrastructure)
  shell: oc get sa -n {{ oc_infra_project }}
  register: sa_result
  changed_when: False

- name: Create SA (Infrastructure)
  shell: oc create sa {{ oc_cs_infra_sa }} -n {{ oc_infra_project }}
  when: not sa_result.stdout | regex_search('^%s\s' % oc_cs_infra_sa, multiline=True)

#- name: Check Cluster Role Bindings
#  shell: >
#    oc get clusterrolebindings -n {{ oc_infra_project }}
#    | grep {{ oc_project }}/default
#  register: crb_result
#  changed_when: False

#- name: Set Roles (default)
#  shell: "{{ item }}"
#  loop:
#  - oc adm policy add-scc-to-user anyuid -z {{ oc_cs_infra_sa }}
#  when: not crb_result.stdout | regex_search('^cluster-admin', multiline=True)
