---

- name: Login (admin)
  shell: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

# Create the ChemCentral service account in the infrastructure project.

- name: Check SA (Infrastructure)
  shell: oc get sa
  register: sa_result
  changed_when: False

- name: Create SA (Infrastructure)
  shell: oc create sa {{ oc_cc_infra_sa }}
  when: not sa_result.stdout | regex_search('^%s\s' % oc_cc_infra_sa, multiline=True)

- name: Check Security Context Constraints
  shell: oc describe scc anyuid
  register: scc_result
  changed_when: False

- name: Set Roles
  shell: "{{ item }}"
  loop:
  - oc adm policy add-scc-to-user anyuid -z {{ oc_cc_infra_sa }}
  when: >-
    not scc_result.stdout
    | regex_search('^\s+Users:\s+\S*:%s:%s' % (oc_infra_project, oc_cc_infra_sa), multiline=True)
