---

- name: Move to Squonk ChemCentral Search Project
  command: oc project {{ oc_cc_project }}
  changed_when: False

- name: Check Databse PVCs (minishift)
  command: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Databse PVCs (minishift)
  shell: >
    oc process
    -p POSTGRESQL_VOLUME_SIZE={{ oc_cc_postgresql_volume_size }}
    -f {{ role_path }}/files/chemcentral-pvc-minishift.yaml
    | oc create -f -
  when: not i_pvc_result.stdout|regex_search('^chemcentral-postgresql-claim\s', multiline=True)

# Wait for claims to become bound...

- name: Wait for Database PVCs to become Bound (minishift)
  shell: oc get pvc/{{ item }} | grep Bound
  delay: 15
  retries: "{{ (oc_pvc_bind_timeout|int / 15)|int }}"
  register: result
  until: result.rc == 0
  loop:
  - chemcentral-postgresql-claim
  when: not i_pvc_result.stdout|regex_search('^chemcentral-postgresql-claim\s', multiline=True)

- name: Check Loader PVCs (minishift)
  command: oc get pvc
  register: i_pvc_result
  changed_when: False

- name: Create Loader PVCs (minishift)
  shell: >
    oc process
    -f {{ role_path }}/files/chemcentral-data-loader-pvc-minishift.yaml
    | oc create -f -
  when: not i_pvc_result.stdout | regex_search('^chemcentral-data-loader-pvc\s', multiline=True)

# Wait for claims to become bound...

- name: Wait for Loader PVCs to become Bound (minishift)
  shell: oc get pvc/{{ item }} | grep Bound
  delay: 15
  retries: "{{ (oc_pvc_bind_timeout|int / 15)|int }}"
  register: result
  until: result.rc == 0
  loop:
  - chemcentral-data-loader-pvc
  when: not i_pvc_result.stdout|regex_search('^chemcentral-data-loader-pvc\s', multiline=True)

