---

# Deletes the loader (Job) if it exists.
# Use this  play to clean-up the loader
# so that you can run another with the same identity.

- name: Login (admin)
  command: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to ChemCentral Search Project
  command: oc project {{ oc_cc_project }}
  changed_when: False

- name: Check Jobs
  command: oc get jobs
  register: jobs_result
  changed_when: False

- name: Delete Loader Job
  command: oc delete job/chemcentral-loader
  when: jobs_result.stdout|regex_search('^chemcentral-loader-%s\s' % oc_cc_loader_marker, multiline=True)
