---

# Deploy the ChemCentral database

- name: Login (admin)
  shell: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Squonk Infrastructure Project
  shell: oc project {{ oc_infra_project }}
  changed_when: False

- name: Check ChemCentral Deployment
  shell: oc get dc
  register: dc_result
  changed_when: False

- name: Create ChemCentral Database
  shell: >
    oc process
    -f {{ role_path }}/files/chemcentral-db.yaml
    -p DB_NAMESPACE={{ oc_infra_project }}
    -p APP_NAMESPACE={{ oc_project }}
    -p APP_SA={{ oc_cc_infra_sa }}
    -p CCDB_CPU_REQUEST={{ oc_cc_postgresql_cpu_request }}
    -p CCDB_MEM_REQUEST={{ oc_cc_postgresql_mem_request }}
    | oc create -f -
  when: not dc_result.stdout | regex_search('^db-chemcentral\s', multiline=True)

# Wait for running pods...

- name: Wait for ChemCentral Database
  shell: oc get po | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 20
  retries: "{{ (pod_ready_timeout | int / 20) | int }}"
  register: result
  until: result.rc == 0
  loop:
  - db-chemcentral
  when: wait_for_pods
  changed_when: False
