---

- name: Move to Squonk Project
  shell: oc project {{ oc_project }}
  changed_when: False
  tags:
  - chemcentral-loader

# Load data into the ChemCentral database.
# This is achieved by launching the loader Job
# which relies on the file in the loader's PVC.
#
# The loader Job can take considerable time
# so the rest is up to you...

- name: Check Jobs
  shell: oc get jobs
  register: jobs_result
  changed_when: False
  tags:
  - chemcentral-loader

- name: Create Loader Job
  shell: >
    oc process
    -f {{ role_path }}/{{ t_dir }}/chemcentral/loader.yaml
    -p LOADER_CLASS={{ loader_class }}
    -p LOADER_FILE={{ loader_file }}
    -p LIMIT={{ loader_limit }}
    | oc create -f -
  when: not jobs_result.stdout | regex_search('^chemcentral-loader\s', multiline=True)
  tags:
  - chemcentral-loader
