---

# Just run these plays...

- import_tasks: create-project.yaml
- import_tasks: create-service-account.yaml

# Some diagnostic debug...
- name: Display volume configuration
  debug:
    msg: >-
      volume_type={{ oc_cc_infra_volume_type }}
      volume_storage_class={{ oc_cc_volume_storage_class }}

# NFS volumes...
- import_tasks: create-nfs-pv-pvc.yaml
  when: oc_cc_infra_volume_type == 'nfs'
- import_tasks: create-data-loader-nfs-pv-pvc.yaml
  when: oc_cc_infra_volume_type == 'nfs'
# Dynamic volumes...
- import_tasks: create-dynamic-pvc.yaml
  when: oc_cc_infra_volume_type == 'dynamic'
# MiniShift volumes...
- import_tasks: create-minishift-pvc.yaml
  when: oc_cc_infra_volume_type == 'minishift'
- import_tasks: patch-minishift.yaml
  when: oc_cc_infra_volume_type == 'minishift'

- import_tasks: deploy-database.yaml
- import_tasks: deploy-search.yaml
