---

# Various checks to do the best we can to make sure
# that the environment is ready for Squonk's ChemCentral data.
# These should be exhaustive tests and may evolve over time.
#
# For example: is there an infrastructure project
# and is there a squonk project?

- name: Login (admin)
  shell: oc login {{ oc_master_hostname }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

# Check the infrastructure project exists...

- name: Collect projects
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Check infrastructure project
  fail:
    msg: >-
      The Squonk Infrastructure project ({{ oc_infra_project }})
      does not exist
  when: oc_infra_project not in projects_result.stdout

- name: Check squonk project
  fail:
    msg: >-
      The Squonk project ({{ oc_project }})
      does not exist
  when: oc_project not in projects_result.stdout
