---

- name: Login (user)
  command: oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Move to ChemCentral Search Project
  command: oc project {{ oc_cc_project }}
  changed_when: False

# Preps the loader data directory with eMolecules SMILES data.
# The loader job should be fast, and so the Job is deleted when complete.
# Any prior job is also deleted at the start of this playbook.

- name: Check Jobs
  command: oc get jobs
  register: jobs_result
  changed_when: False

- name: Delete Pre-Exisiting Loader Prep
  command: oc delete all,cm,pvc,secrets --selector template=prep-loader-emolecules
  when: jobs_result.stdout|regex_search('^chemcentral-prep-loader-emolecules\s', multiline=True)

- name: Run Pre-Loader
  shell: >
    oc process
    -f {{ role_path }}/files/prep-loader-emolecules.yaml
    -p APP_NAMESPACE={{ oc_cc_project }}
    -p APP_SA={{ oc_cc_infra_sa }}
    | oc create -f -

- name: Wait for loader preparation
  shell: oc describe jobs/chemcentral-prep-loader-emolecules | grep '1 Succeeded'  | grep 1
  delay: 10
  retries: "{{ (oc_pod_ready_timeout|int / 10)|int }}"
  register: result
  until: result.rc == 0
  changed_when: False

- name: Remove loader preparation
  command: oc delete all,cm,pvc,secrets --selector template=prep-loader-emolecules
