---

# Un-deploy (uninstall) the Squonk ChemCentral application.
#
# This consists of un-deploying the application components from the squonk
# project and the related parts of the squonk infrastructure project.

- name: Delete Squonk ChemCentral?
  pause:
    prompt: |-
      Delete ChemCentral and related databases from {{ oc_master_url }}?
      Hit return to delete ChemCentral.
      Hit Ctrl+c and then "a" if you've changed your mind

- name: Login (admin)
  command: oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Check Project
  command: oc get projects
  register: projects_result
  changed_when: False

- name: Set project fact
  set_fact:
    project_exists: "{{ (projects_result.stdout|regex_search('^%s\\s.*Active$' % oc_cc_project, multiline=True) or '')|length > 0 }}"

- name: Delete ChemCentral Project
  shell: oc delete project/{{ oc_cc_project }}
  when: project_exists|bool

- name: Wait for ChemCentral project deletion
  shell: oc get projects
  register: pj_cmd
  retries: 20
  delay: 30
  until: not pj_cmd.stdout|regex_search('^%s\s' % oc_cc_project, multiline=True)
  when: project_exists|bool
  changed_when: False

# Delete the PVs (NFS)...

- name: Check ChemCentral PVs (nfs)
  command: oc get pv
  register: pv_result
  changed_when: False
  when: oc_cc_infra_volume_type == 'nfs'

- name: Delete ChemCentral PVs (nfs)
  command: oc delete pv/{{ item }}
  loop:
  - pv-chemcentral-postgresql
  - pv-chemcentral-loader
  when:
  - oc_cc_infra_volume_type == 'nfs'
  - pv_result.stdout|regex_search('^%s\s' % item, multiline=True)
