---

kind: Template
apiVersion: v1
metadata:
  name: chemcentral-data-loader-pvc-minishift
  annotations:
    description: Data loader Persistent Volume using Minishift
    tags: squonk,pv
labels:
  template: chemcentral-data-loader-pvc-minishift
  app: chemcentral

parameters:

- name: APP_NAMESPACE
  value: squonk

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: chemcentral-data-loader-pvc
    namespace: ${APP_NAMESPACE}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

