---

# The Infrastructure Persistance for Minishift.
# PVs are already provided by Minishift so we only need to create PVCs
#
# oc process -f chemcentral-pvc-minishift.yaml | oc create -f -
# oc delete pvc --selector template=chemcentral-pvc-minishift

kind: Template
apiVersion: v1
metadata:
  name: chemcentral-persistence-minishift
  annotations:
    description: Chemcentral Persistent Volume Claims for Minishift
    tags: squonk,chemcentral,pvc
labels:
  template: chemcentral-pvc-minishift

parameters:

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: chemcentral-postgresql-claim
    labels:
      application: chemcentral
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"


