version: '2.1'
        
services:

    ################# nginx ##########################################################
    # Acts as reverse proxy
    # create self-signed SSL cert/key using:
    # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout images/nginx/certs/squonk/privkey.pem -out images/nginx/certs/squonk/fullchain.pem
    nginx:
        image: nginx:1.13
        restart: on-failure:10
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./images/nginx/default.ssl.conf:/etc/nginx/conf.d/default.conf:ro
        - ./images/nginx/certs/:/etc/nginx/certs/:ro
        - ./images/nginx/sites/index.html:/usr/share/nginx/html/index.html:ro
        - ./images/nginx/sites/squonk.it/html/:/usr/share/nginx/html/squonk.it/html/:ro
        networks:
        - squonk_front
        depends_on:
            keycloak:
                condition: service_healthy


