version: '2.1'

services:

    portal:
        ports:
        - 8080:8080

    postgres:
        ports:
        - "5432:5432"

    coreservices:
        ports:
        - "8091:8080"

    chemservices:
        ports:
        - "8092:8080"

    chemcentral-search:
        ports:
        - "8093:8080"

    jobexecutor:
        image: squonk/jobexecutor:${TAG}
        ports:
        - "8094:8080"
        environment:
            SQUONK_JOBEXECUTOR_ALLOW_UNAUTHENTICATED: "true"

