version: '2.1'
        
services:
        
    ################# nginx ##########################################################
    # Add the IM web site
    #
    nginx:
        volumes:
        - ./images/nginx/informaticsmatters.com.conf:/etc/nginx/conf.d/informaticsmatters.com.conf:ro,z
        - ./images/nginx/sites/informaticsmatters.com/jekyll/website/_site/:/usr/share/nginx/html/www.informaticsmatters.com/html/:ro,z
 
