version: '2.1'
        
services:
 
 
    ################# xwiki container ###################################################
    # available on http://${PUBLIC_HOST}/xwiki
    xwiki:
        image: squonk/xwiki
        restart: on-failure:10
        volumes:
        - ./data/xwiki:/var/local/xwiki
        - ./images/xwiki/keycloak.json:/usr/local/tomcat/webapps/xwiki/WEB-INF/keycloak.json
        depends_on:
        - keycloak
        - postgres
        environment:
            PUBLIC_HOST:
            KEYCLOAK_SERVER_URL:
            POSTGRES_XWIKI_PASSWORD:
        networks:
        - squonk_front
        - squonk_back
        
    ################# nginx ##########################################################
    # Acts as reverse proxy
    # place the privkey.pem and fullchain.pem certificates in the images/nginx/certs/squonk.it/ directory
    # and generate Strong Diffie-Hellman Group like this:
    # openssl dhparam -out images/nginx/certs/squonk.it/dhparam.pem 2048
    nginx:
        image: nginx:1.13
        restart: on-failure:10
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
        - ./images/nginx/default.site.conf:/etc/nginx/conf.d/default.conf:ro,Z
        - ./images/nginx/certs/:/etc/nginx/certs/:ro,Z
        - ./images/nginx/xwiki.conf:/etc/nginx/snippets/xwiki.conf:ro,Z
        - ./images/nginx/sites/squonk.it/html/:/usr/share/nginx/html/squonk.it/html/:ro,Z
        - ./images/nginx/informaticsmatters.com.conf:/etc/nginx/conf.d/informaticsmatters.com.conf:ro,Z
        - ./images/nginx/sites/informaticsmatters.com/jekyll/website/_site/:/usr/share/nginx/html/www.informaticsmatters.com/html/:ro,Z
        networks:
        - squonk_front
 
