version: '2.1'

services:

    portal:
        ports:
        - 8080:8080

    postgres:
        ports:
        - "5432:5432"

    coreservices:
        ports:
        - "8091:8080"

    chemservices:
        ports:
        - "8092:8080"

    chemcentral-search:
        ports:
        - "8093:8080"

    cellexecutor:
        environment:
            FRAGNET_SEARCH_BASE_URL: "http://fragnet-services:8080/fragnet-search"

    fragnet-services:
        image: squonk/fragnet-services:latest
        environment:
            NEO4J_PASSWORD:
            NEO4J_SERVER:
        ports:
            - "8094:8080"
        networks:
            - squonk_back
