---

# A simple pod that you can use to mount a volume.
# A handy mechanism to connect into the cluster and
# poke-around with data in a volume.
#
# The pod uses yauritux/busybox-curl and mounts the volume
# into the pod at '/volume' then does a 'tail -f /dev/null'
# (essentially sleeping forever) ... plenty of time to connect
# and poke around.
#
# You can rsync into the volume...
#   oc rsync ./dir volume-pod:/volume
# Or out of it...
#   oc rsync volume-pod:/volume ./dir
#
# oc process -f volume-pod.yaml -p PVC_NAME=blob | oc create -f -
# oc delete po --selector template=volume-po

kind: Template
apiVersion: v1
metadata:
  name: volume-pod
labels:
  template: volume-pod

parameters:

- name: PVC_NAME
  required: yes

objects:

- kind: Pod
  apiVersion: v1
  metadata:
    name: volume-pod
  spec:
    containers:
    - image: yauritux/busybox-curl
      name: volume-pod
      command:
      - '/bin/tail'
      - '-f'
      - '/dev/null'
      volumeMounts:
      - mountPath: /volume
        name: volume-dir
    volumes:
    - name: volume-dir
      persistentVolumeClaim:
        claimName: ${PVC_NAME}
