version: '2.1'

services:

    chemcentral:
        image: informaticsmatters/rdkit-cartridge-debian:Release_2020_03_1
        volumes:
        - ./init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh:ro,Z
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432

