---

kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-sso
    tags: keycloak-secrets
    openshift.io/display-name: Keycloak Secrets
    openshift.io/provider-display-name: Informatics Matters Ltd.
    description: >-
      Keycloak secrets
    template.openshift.io/long-description: >-
      Keycloak secrets for use by keycloak and other applications
  name: keycloak-secrets
labels:
  template: keycloak-secrets
  app: keycloak-secrets
message: >-
  Keycloak secrets have been created in your project. The username/password for
  accessing the Keycloak is ${SSO_ADMIN_USERNAME}/${SSO_ADMIN_PASSWORD}.
  This is stored in a secret named keycloak-secrets.

parameters:

- displayName: RH-SSO Administrator Username
  description: RH-SSO Server administrator username
  name: SSO_ADMIN_USERNAME
  value: admin
  required: true
- displayName: RH-SSO Administrator Password
  description: RH-SSO Server administrator password
  name: SSO_ADMIN_PASSWORD
  from: "[a-zA-Z0-9]{20}"
  generate: expression
  required: true

objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: keycloak-secrets
    labels:
      application: keycloak-secrets
  stringData:
    sso-admin-user: "${SSO_ADMIN_USERNAME}"
    sso-admin-password: "${SSO_ADMIN_PASSWORD}"
