---

kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-sso
    tags: postgres-secrets
    openshift.io/display-name: PostgreSQL (Persistent) Secrets
    openshift.io/provider-display-name: Informatics Matters Ltd.
    description: >-
      PostgreSQL secrets for the database
    template.openshift.io/long-description: >-
      PostgreSQL database secrets for use by keycloak and other applications
  name: postgresql-secrets
labels:
  template: postgresql-secrets
  app: postgresql-secrets
message: >-
  PostgreSQL secrets have been created in your project. The username/password for
  accessing the PostgreSQL database "${DB_DATABASE}" is ${DB_USERNAME}/${DB_PASSWORD}.
  This is stored in a secret named postgresql-secrets.

parameters:

- displayName: Database Name
  description: Database name
  name: DB_DATABASE
  value: keycloak
  required: true
- displayName: Database Admin Username
  description: Database Admin user name
  name: DB_ADMIN_USERNAME
  value: postgres
  required: true
- displayName: Database Admin Password
  description: Database postgres user password
  name: DB_ADMIN_PASSWORD
  from: "[a-zA-Z0-9]{20}"
  generate: expression
  required: true
- displayName: Database Username
  description: Database user name
  name: DB_USERNAME
  from: user[a-zA-Z0-9]{3}
  generate: expression
  required: true
- displayName: Database Password
  description: Database user password
  name: DB_PASSWORD
  from: "[a-zA-Z0-9]{20}"
  generate: expression
  required: true

objects:

# NOTE: As it's currently hard-coded,
#       if you modify the 'database-service' secret
#       you *MUST* check the rest of the project.

- kind: Secret
  apiVersion: v1
  metadata:
    name: postgresql-secrets
    labels:
      application: postgresql-secrets
  stringData:
    database-service: db-postgresql
    database-user: "${DB_USERNAME}"
    database-password: "${DB_PASSWORD}"
    database-admin-user: "${DB_ADMIN_USERNAME}"
    database-admin-password: "${DB_ADMIN_PASSWORD}"
    database-name: "${DB_DATABASE}"
