---
name: publish tag

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# ORG_GRADLE_PROJECT_CXNMAVENPASSWORD
# ORG_GRADLE_PROJECT_CXNMAVENREPOSITORYURL
# ORG_GRADLE_PROJECT_CXNMAVENUSER
#
# SQUONK_DECRYPTION_KEY
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    tags:
    - '**'

env:
  ORG_GRADLE_PROJECT_cxnMavenPassword: ${{ secrets.ORG_GRADLE_PROJECT_CXNMAVENPASSWORD }}
  ORG_GRADLE_PROJECT_cxnMavenRepositoryUrl: ${{ secrets.ORG_GRADLE_PROJECT_CXNMAVENREPOSITORYURL }}
  ORG_GRADLE_PROJECT_cxnMavenUser: ${{ secrets.ORG_GRADLE_PROJECT_CXNMAVENUSER }}
  SQUONK_DECRYPTION_KEY: ${{ secrets.SQUONK_DECRYPTION_KEY }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      run: ./gradlew dockerBuildImages -x test
      working-directory: components
      env:
        SQUONK_IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: |
        docker push squonk/chemservices-basic:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/chemcentral-search:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/coreservices:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/cellexecutor:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/jobexecutor-keycloak:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/chemcentral-loader:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/flyway:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/flyway-2:${{ env.GITHUB_REF_SLUG }}
