---
name: test and build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.
# Here we test the code and build container images but don't push them
# and therefore do not require docker credentials.

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - 'master'

env:
  CHEMAXON_LIBRARY_ABSENT: 'yes'
  SQUONK_DOCKER_WORK_DIR: $GITHUB_WORKSPACE/tmp
  SQUONK_IMAGE_TAG: latest

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Write work-dir to env-file
      run:  echo SQUONK_DOCKER_WORK_DIR=$(echo ${{ github.workspace }}/tmp) >> $GITHUB_ENV
    - name: Test
      run: |
        curl -s get.sdkman.io | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install groovy
        ./gradlew installChemaxonLicenseToHome
        ./gradlew installChemaxonLibrary
        ./gradlew build
      working-directory: components
    - name: Build
      run: ./gradlew dockerBuildImages -x test
      working-directory: components
